### ISSUE TITLE
Why is there no maintenance in the vapor / documentation issue?The question was submitted for a long time ?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1014]
**https://github.com/vapor/documentation/pull/144

This is the request that I submitted about ten days ago, adding Simplified Chinese translations and fixing path access failures .**

https://github.com/vapor/documentation/tree/master/1.5  
![a](https://cloud.githubusercontent.com/assets/16829428/26192200/533ecd2a-3be3-11e7-8b78-7f62761e8ba1.png)

Here, when you click here when prompted not found.

**Comment by tanner0101** [comment]
Docs have been rewritten for 2.0: https://docs.vapor.codes/2.0/

We could consider translating them again. However, I'd rather look into something like: https://translate.google.com/manager/website/ so we don't have to continually deal with outdated translations. 

It's also worth noting several websites and Google Chrome itself can automatically translate pages. So I don't know how useful a button would be. 

Closing this issue here since it relates to documentation and not the vapor framework itself.

**Comment by Jinxiansen** [comment]
👍👍👍
