### ISSUE TITLE
Fluent select specific columns from table

### ISSUE THREAD

**Issue by lorsulic** [vapor/vapor#1032]
### Introduction

It seems it is not possible to fetch only specific columns using fluent, so something like "SELECT column_name FROM Table;"

### Motivation

It is a basic data fetching approach. Avoiding to fetch everything every time if no filter comparison or filter subset is used.

### Proposed solution

I would expect to use e.g. 
`try MyModel.makeQuery().select("column_name").all()`
or with more parameters:
`try MyModel.maleQuery().select("column_name1","column_name2").all()`

**Comment by tanner0101** [comment]
This issue has been brought up a few times. Given Fluent's strictly model-based approach to querying the database, it doesn't make much sense to all selective querying. If not all of the information is present in the query, the models will not be able to initialize, and the query will fail. 

It would make more sense to do these types of selective queries as raw queries. Potentially some day Fluent might have a layer below `Fluent.Query` that is more flexible and returns `Row`s instead of models. However that's a pretty long term goal given how integrated the Model type is. Definitely Fluent 3.0 at least.
