### ISSUE TITLE
Problem with query with points (.)

### ISSUE THREAD

**Issue by fernandolicon** [vapor/vapor#1041]
* Vapor Version: 2.0.0
* OS: macOS
* OS Version: 10.12.15 
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

When receiving a request with points in the query, for example `localhost:8080/getData?foo.bar=foo` if I try to get `request.data["foo.bar"]` I should get `foo`.

### Current Behavior

Fetching the value returns a `nil` instead of the value, if I remove the point, like this `localhost:8080/getData?foobar=foo` and try to get `request.data["foobar"]` I get the correct value.

### How to Reproduce

Implement the next method and do a get request to `localhost:8080/getData?foo.bar=foo` 

```
drop.get("data") { request in
    drop.console.print("Received get", newLine: true)
    let data = request.data["foo.bar"]
    print(data)
    
    return Response(status: .ok)
}
```

The console would print nil.

--------------------------

So here, I'm not sure if my problem is that I don't know how to fetch correctly the data (maybe that's not the key I should ask for) or if it's a problem with the framework. I've tried getting `request.data["foo", "bar"]` and `request.data["foo"]["bar"]` but the result is the same.

Thanks,

**Comment by LoganWright** [comment]
@fernandolicon The issue here is the way we were treating dots. We changed this slightly in v2, so the confusion makes sense. Since `.` inclusion in a key that is not nested is so incredibly rare, we don't support it by default, and instead make it an opt in via a type called `DotKey`. For example:

```swift
let _ = json[DotKey("foo.bar")]
```

If you're using this quite a bit, I might make an extension like:

```swift
extension String {
    var dk: DotKey {
        return DotKey(self)
    }
}
```

Then you could do:

```swift
let _ = json["foo.bar".dk]
```

Alternatively, a custom subscript could be used that converts to DotKey internally 👍 

Let me know if you have any other questions, and thanks for participating in Vapor!

**Comment by fernandolicon** [comment]
@LoganWright Hey, thanks for the response. I'm working with Facebook Chatbots and they send the keys with points, it was weird for me as well but I can't change it.

Thanks, the solution works!

Keep the good work 👍
