### ISSUE TITLE
1.5 mysql

### ISSUE THREAD

**Issue by sunnyNH** [vapor/vapor#1080]
MAC environment

1.5version
Linking ./.build/debug/App
ld: library not found for -lmysqlclient for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)

2.0version
Won't appear this problem

**Comment by vzsg** [comment]
That’s expected behavior.

The v1.5 version requires extra compilation flags to find the mysqlclient library, which were added by the v1 toolbox whenever you called `vapor build` or `vapor xcode`.

Compared to this, the v2 toolbox no longer adds the flags, since the v2 MySQL driver can find everything automatically using pkg-config.

So if you still need to work with 1.5 projects, you should install `vapor1` with Homebrew, and use `vapor1 build`, `vapor1 xcode`, etc. to build your old project; and use `vapor build` for v2 projects only.

**Comment by sunnyNH** [comment]
Why Ubuntu 1.5 and 2.0 will not appear this problem can be built

**Comment by vzsg** [comment]
Because on Linux, libmysqlclient-dev is installed under /usr/lib, and Swift can find it by itself.

**Comment by sunnyNH** [comment]
Thanks for vapor is great！
