### ISSUE TITLE
Extend makeResponse() to support statuses other than Status.ok

### ISSUE THREAD

**Issue by plummer** [vapor/vapor#1156]
## Name of Feature

* Author(s): [Andrew Plummer](https://github.com/plummer)

### Introduction

A change to support easily returning responses with makeResponse with other statuses than ok for all response types.

### Motivation

It is common to return a code other than 200 along with view data, for example returning a 500 error with a HTML page for the user. It would be convenient to remove the hardcoded Status.ok from makeResponse methods to support this. This applies to JSON and other response types too.

### Proposed solution

Add a status parameter (with a default argument of Status.ok so there will be no change to existing code), replacing the hardcoded Status.ok.

### Code snippets

Usage example, with status provided:

```
// Will return response with I'm a teapot status

return try droplet.view.make(
  "Templates/Error/418"
).makeResponse(status: .imATeapot)
```
Usage example, without status provided (no change):

```
// Will return response with 200 status (like usual)

return try droplet.view.make(
  "Templates/Error/418"
).makeResponse()
```

### Impact

Use of default argument for status of .ok will prevent changes to existing code being required. Autocomplete will have an additional option where `status: Status` can be provided.

### Alternatives considered

Creating an additional method.

**Comment by plummer** [comment]
Happy to make the PR for this one, just wanted to make the issue to understand if there is support for this change in the repo. Also wanted to see if there was any additional context (this might even already exist) that i should understand.

Thanks!

**Comment by Joannis** [comment]
```swift
extension ResponseRepresentable {
    public func makeResponse(status: Status) throws -> Response {
        let response = try makeResponse()
        response.status = status
        return response
    }
}
```

**Comment by plummer** [comment]
Thanks @Joannis , this is what I'm suggesting with the small change of a default parameter:

```
extension ResponseRepresentable {
  public func makeResponse(status: Status = .ok) throws -> Response {
    let response = try makeResponse()
    response.status = status
    return response
  }
}
```

Then a case of updating the other various usages for JSON etc.

**Comment by Joannis** [comment]
Changing the requirements in the protocol is extremely breaking and can't be done in Vapor 2, I'm afraid. Making a response from a `Status` is not a protocol that's primarily intended to be called by the web developer, but rather to be called by Vapor itself.

Normally you'd need to return a `Response` in every route, so instead of returning "Hello world" like this:

```swift
drop.get { request in
  return "Hello world"
}
```

You need to return a concrete Response.

```swift
drop.get { request in 
  return Response(body: "Hello world")
}
```

So `ResponseRepresentable` is here to make this part of the API easier/simpler. But you can still return a `Response` if you need more control.

[However, this is already changed in Vapor 3 in some way.](https://github.com/vapor/vapor/blob/application-helpers/Sources/HTTP/Response/Response.swift#L88)

The one problem with `ResponseRepresentable` is the lack of context, which we changed above.

**Comment by tanner0101** [comment]
Vapor 3 supports this now with the syntax:
```swift
req.makeResponse(http: .init(status: .notFound))
```
