### ISSUE TITLE
Make Float,Double as Parameterizable

### ISSUE THREAD

**Issue by arunbeee** [vapor/vapor#1245]
* Vapor Version: 2.2.2
* OS: Mac OS
* OS Version: 10.13.1
* Vapor Toolbox Version:3.1.2

### Expected Behavior

Ability to accept numbers greater than the range of Int and also support decimal values in the 

### Current Behavior

As Double and Float do not conform to  Parameteriazable, they cannot be used as type safe parameter. The only way is to fetch those values is using manual routing parameters and converting them.

**Comment by Joannis** [comment]
How do you suggest we treat decimals: `5.16` or `5,16`?

Also; how does this fit in with regular URLs? `/user/arunbeee/profile` can only be read one way. `,` is a reserved character and would need to be percent encoded [as per RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2), so it can provide problems for users.

**Comment by arunbeee** [comment]
Double or Float by implementation only supports dot notation for representing decimal values in Swift. Hence, any other notation other than the dot notation, will throw a 404 error.

**Comment by julmaz** [comment]
maybe a bit late but its as easy as you think

just let the Type Double conform the protocol "Parameterizable" and set the uniqueSlug to "Double";
and set the make for func to 

guard let double = Double(parameter) else { throw RouterError.invalidParameter }
return double 


---
because if you're just using it for simple api routing you will get the Double with a dot not a comma 

so take this and it will work

**Comment by tanner0101** [comment]
This was added in vapor/routing 👍
