### ISSUE TITLE
Announce when server is ready to serve requests - 3.0 feature req

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1353]
like in the old Vapor, now we have to keep pressing refresh until we get some response

**Comment by Joannis** [comment]
@rafiki270 since Vapor 3 is async, we don't know the exact moment when we'll be ready. But we do print the message after we've done a `bind` for the socket and start accepting requests. There is, however, a problem with requests not being read for new connections. This problem is to be fixed in the next alpha.
