### ISSUE TITLE
Websockets neither receive nor send

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1490]
* Vapor Version: beta
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior
Websockets should receive messages

### Current Behavior
Websockets do not receive messages

### How to Reproduce
Using a simple echo route
```
router.websocket("echo") { (req, ws) in
    ws.onString({ (ws, msg) in
        ws.send(string: msg)
    })
}
```
`ws.send(string: msg)` is never hit.

**Comment by gwynne** [comment]
The underlying cause of this appears to be a "ready" promise which is never completed, causing the socket to never process any further events, including EOF, which ultimately breaks the entire state machine of the streams and leads to a CPU-maxing infinite loop of `kevent()` returning `EV_EOF` for the same source endlessly.

The missing promise completion happens in `HTTPResponderStream.input()` (HTTPResponder.swift line 46) when a WebSocket upgrade closure is available. Normally, a responder's completion is chained by passing the result downstream on line 83 (`downstream.input(.next(res, nextRequest))`). However, when an `onUpgrade` closure is provided, the code instead passes a new `receivedResponse` promise to `downstream`, _but never does anything with `nextRequest`!_ As a result, `downstreamIsReady`, back up in `TCPSocketSource`, never becomes true again - it can only become true upon completion of the promise. This prevents `readSourceSignal()` from ever calling `readData()` again, whether the source has been EOF'd (`cancelIsPending`) or not. When the source becomes readable while the socket is still open, it just defers the readability signal, ultimately suspending the read source. When the socket EOF's, the suspend logic no longer applies, and the code simply returns, trapping `kevent()` in an infinite loop of signaling the source again and again because no action is ever taken. (In the normal course of events, the EOF would cause a `readData()`, which would trigger an EOF from `read()`, closing the socket and correctly canceling the socket source.)

I don't understand the streams machinery well enough to know when and how to properly complete the `nextRequest` promise, so I leave it to @tanner0101 and/or @Joannis to find an actual fix.

**Comment by gwynne** [comment]
Worth noting that if I manually complete the `nextRequest` promise, receiving works but sending still doesn't. Probably the wrong solution anyway :).

**Comment by SandorDobi** [comment]
related to #1488 
the first example with bcrypthasher is related here

**Comment by siemensikkema** [comment]
I was able to get websockets to work (send and receive) by following @gwynne 's suggestion of completing the `nextRequest` (on line [81]( https://github.com/vapor/engine/blob/291640d20350f6ab889fdc915e31d29c4bd88e73/Sources/HTTP/Server/HTTPResponder.swift#L81)). I don't have the issue of the CPU maxing out - possibly because of fixes elsewhere.
@tanner0101 @Joannis I have no idea of whether this is the right solution but at least it enables me to explore websockets further.

**Comment by Joannis** [comment]
I've been meaning to avoid that workaround, but I guess it's the only viable solution.

**Comment by Joannis** [comment]
Fixed in the latest Engine, there was no other fix other than what was already posted here.
