### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by linqingmo** [vapor/vapor#1515]
### Steps to reproduce
```swift
router.post("login") { req -> Response in
    let username: String = try req.content.get(at: "username").blockingAwait()
    let password: String = try req.content.get(at: "password").blockingAwait()
    print(username)
    print(password)
    return req.makeResponse()
}
```
### Expected behavior
Get username and password immediately.
### Actual behavior
It will time out when request several times.
### Environment
* Vapor Toolbox: 3.1.4
* Vapor Framework: 3.0.0-rc.1
* OS version: macOS High Sierra

**Comment by Joannis** [comment]
@linqingmo `blockingAwait` cannot be used this way. The goal of `blockingAwait` is to block the _current_ thread until results have been received. If the current thread is the same thread where the data should be arriving from you've deadlocked the thread.

It's primary use case is unit tests and the `await` functions should be avoided otherwise.

**Comment by linqingmo** [comment]
@Joannis Thanks.
