### ISSUE TITLE
dyld: Symbol not found: __TMSS

### ISSUE THREAD

**Issue by Frohmen** [vapor/vapor#1545]
When I try to run vapor in terminal I get the following error:

dyld: Symbol not found: __TMSS
  Referenced from: /usr/local/bin/vapor
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/vapor
Abort trap: 6

**Comment by vzsg** [comment]
This error usually happens if you have a really old version of the toolbox installed. There were a few problematic builds that didn't statically link the Swift Standard Library, so the system would try to use the currently available one in Xcode – which are not compatible between even minor versions...

Try force-upgrading the toolbox with homebrew. `brew install -force vapor/tap/vapor`

**Comment by tanner0101** [comment]
What @vzsg said should work 👍
