### ISSUE TITLE
Fetching of https://github.com/apple/swift-nio-ssl-support.git never ends

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/vapor#1571]
Fetching of https://github.com/apple/swift-nio-ssl-support.git never ends in vapor 3.0.0-rc.2.1

### Steps to reproduce

```swift
let package = Package(
   name: "TennisCup",
   products: [
      .library(name: "App", targets: ["App"])
      ],
   dependencies: [
      .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc.2.1"),
      .package(url: "https://github.com/vapor/fluent-provider.git", from: "1.0.0"),
      .package(url: "https://github.com/vapor/auth-provider.git", from: "1.0.0"),
      .package(url: "https://github.com/vapor/leaf-provider.git", from: "1.0.0"),
      .package(url: "https://github.com/vapor-community/postgresql-provider.git", from: "2.0.0"),
      .package(url: "https://github.com/vapor-community/CSRF.git", from: "1.0.0")
   ],
   targets: [
      .target(name: "App", dependencies: [
         "Vapor",
         "FluentProvider",
         "AuthProvider",
         "LeafProvider",
         "PostgreSQLProvider",
         "CSRF"
         ]),
      .target(name: "Run", dependencies: ["App"]),
      ]
)
```

### Expected behavior

```swift build``` and ```vapor xcode``` should complete

### Actual behavior

Fetching of swift-nio-ssl-support.git  never ends

### Environment

* Vapor Framework version: vapor 3.0.0-rc.2.1
* Vapor Toolbox: 3.1.4
* OS version: 10.13.2

```swift --version```
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

**Comment by 0xTim** [comment]
@Igor-Palaguta your Package.swift is all kinds of conflicted! SPM can't resolve the dependencies which is why it is hanging. Are you trying to pull in the Vapor 3 RC or Vapor 2? 

If you are trying to pull in the Vapor 3 RC you are going to need to make some changes:

* There are no providers anymore - you pull in Auth and Leaf directly.
* If you want to use Fluent with Postgres you just need to depend on `fluent-postgresql`
* The CSRF package depends on Vapor 2 - there isn't a Vapor 3 version yet. You can check what version each package relies on by looking in its manifest - https://github.com/vapor-community/CSRF/blob/master/Package%40swift-4.swift#L11

If you want Vapor 3 have a look at the API template's manifest on the beta branch - it should give you a starting point https://github.com/vapor/api-template/blob/beta/Package.swift

**Comment by Igor-Palaguta** [comment]
@0xTim Thanks! I thought SPM will complain about conflicts and not hang.

**Comment by 0xTim** [comment]
Yeah it’s supposed to...unfortunately it doesn’t always happen!
