### ISSUE TITLE
Add implicit return type to flatMap async method

### ISSUE THREAD

**Issue by mandrusiaks** [vapor/vapor#1606]
It would be great if the async transforming method `flatMap` followed the existing Swift conventions with implicit return type. Swift developers are already familiar with this syntax and it allows unnecessary code to be cut out. This would mean not needing to specify the type for each use of `flatMap`.

Current Syntax:
```
// Example from template
return try req.parameter(Todo.self).flatMap(to: Void.self) { $0.delete(on: req) }
.transform(to: .ok)

// Non-functional example, just for illustration
return try req.parameter(Todo.self).flatMap(to: String.self) { $0.title }
            .flatMap(to: Int.self) { $0.count }
            .flatMap(to: MyCustomType.self) { ... }
            .flatMap(to: Void.self) { $0.delete(on: req) }
            .transform(to: .ok)
```

Suggested Syntax:
```
// Example from template
return try req.parameter(Todo.self).flatMap { $0.delete(on: req) }
            .transform(to: .ok)

// Non-functional example, just for illustration
return try req.parameter(Todo.self).flatMap { $0.title }
            .flatMap { $0.count }
            .flatMap { ... }
            .flatMap { $0.delete(on: req) }
            .transform(to: .ok)
```

**Comment by 0xTim** [comment]
This was how things were originally in the beginning. The issue was that the Swift compiler gave up with any kind of error and the error messages were so far from the truth that it was counterproductive! Swift's type inference basically isn't up to the join so for anything past a one liner you have to declare the return type anyway

**Comment by twof** [comment]
What you're looking for exists, it's just called `.then { }` :)

The reason it isn't called `.flatMap { }` is that it's following Swift-NIO's conventions
https://github.com/apple/swift-nio/issues/213

**Comment by tanner0101** [comment]
`.then { }` doesn't allow throwing inside of it though. I'm thinking it could be beneficial to put the default argument here for flatMap since it seems NIO is committing to that format. NIO already offers map which does not require an argument so it might seem confusing to users that they can't do the same with flatMap.

**Comment by tanner0101** [comment]
This was added in Core 3.1.4
