### ISSUE TITLE
Crash in datemiddleware

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1628]
https://files.slack.com/files-pri/T0N650MLL-FA81PHX5X/image.png

Unfortunately I don't have anything else yet :(

**Comment by tanner0101** [comment]
This might be an issue with DateMiddleware not getting created separately for each event loop. Could you share your configure.swift code @rafiki270?

**Comment by rafiki270** [comment]
There is few more configure methods in play actually:

It goes like this:
https://github.com/LiveUI/Boost/blob/master/Sources/Run/main.swift
https://github.com/LiveUI/BoostCore/blob/b8c3ffc6a2ec46d016dc59e98a33d6966e0845d5/Sources/BoostCore/BoostCore.swift#L99
https://github.com/LiveUI/ApiCore/blob/a9a4aea3181901ac3d73eb97b2e0503212e05d02/Sources/ApiCore/ApiCore.swift#L54

**Comment by rafiki270** [comment]
Stack with asan

**Comment by tanner0101** [comment]
@rafiki270 [this line](https://github.com/LiveUI/ApiCore/blob/a9a4aea3181901ac3d73eb97b2e0503212e05d02/Sources/ApiCore/ApiCore.swift#L55) is the problem. `DateMiddleware` is not thread safe, you must use factory init so that a new copy will be created for each event loop.

You can register like this:

```swift
services.register(DateMiddleware.self)
```

Or just use `Services.default()` and it will already be registered.

**Comment by tanner0101** [comment]
See the linked commit above. In 3.0.0 the `DateMiddleware.init()` will be made private and a new assertion has been added to ensure no multi-threading is happening. 👍

**Comment by rafiki270** [comment]
I can't register like `services.register(DateMiddleware.self)` as `Argument type 'DateMiddleware.Type' does not conform to expected type 'ServiceFactory'? :( @tanner
