### ISSUE TITLE
[Feature request] Early Hints in Vapor

### ISSUE THREAD

**Issue by proyb6** [vapor/vapor#1709]
Does Vapor planning to support Early Hints that Apache and H2O supported, Rail 5.2 is currently on beta.

https://tools.ietf.org/html/draft-kazuho-early-hints-status-code-00

Please use language translation:
https://blog.jxck.io/entries/2016-12-16/103-early-hints.html
https://asnokaze.hatenablog.com/entry/20161205/1480864808

For simple reading:
http://hanamirb.org/guides/1.2/projects/http2-early-hints/

**Comment by 0xTim** [comment]
There are a few things to this - to start it's still a draft so support _could_ be cumbersome.
Second Vapor doesn't yet support HTTP/2 which this proposal relies on (since NIO doesn't support it).
Finally - and most importantly - this would probably need support from NIO to work, I imagine they would end up doing most of the heavy lifting.

PS this seems to be wholly related to front-end projects so might actually be isolated to only Leaf/TemplateKit

**Comment by proyb6** [comment]
I would recommend testing with H2O proxy/web server since the author, Kazuho, drafted Early Hints.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
