### ISSUE TITLE
how to regi a router with user del by id or ids?

### ISSUE THREAD

**Issue by hydyy** [vapor/vapor#1730]
i need a post to receive a param id or ids, how to do that?

**Comment by LoganWright** [comment]
```swift
router.post("path", String.parameter) { req in 
    let id = try req.parameters.next(String.self)
    ...
}
```

Or if you have fluent model id that you're receiving, it's automated

```swift
router.post("path", Model.parameter) { req in 
    let model = try req.parameters.next(Model.self)

```

It is slightly odd to post an ID since it would assume an object already exists. Not sure what you're doing, but thought I'd mention that. If you're editing an object, a PATCH is more common.

You can usually get better support for these types of questions in our discord: vapor.team
