### ISSUE TITLE
FoundationClient does not preserve the final URL of the response

### ISSUE THREAD

**Issue by proggeramlug** [vapor/vapor#1751]
When redirection is involved in sending an HTTP request, as it often is, it is sometimes helpful to know the URL that was retrieved last, after all redirections that were followed (if any). This information is available to `FoundationClient` in the url property of the `HTTPURLResponse` returned by `URLSession`, but is lost due to lacking any representation in `Vapor.Response` or `HTTP.HTTPResponse`. Vapor should add a field to one of these structures (probably `HTTPResponse`) to preserve the final URL for clients who need to know.

**Comment by tanner0101** [comment]
This would probably be a good situation to use `URLSession` directly. Potentially Vapor could consider exposing the methods for converting to / from Vapor's HTTP message type from a foundation request. 

`HTTPResponse` should remain fairly specialized for delivering responses _from_ the application's HTTP server. We should be careful about what we add there since it has the potential to effect the server's raw performance. 

Another possibility that might be worth looking into is separating the structs (`HTTPServerResponse` and `HTTPClientResponse`). This is something that NIO does internally and it would allow us to specialize them more. 

Also, can you link the relevant property on `HTTPURLResponse` that has the information you want? I'd be interested to see how it's implemented.

**Comment by proggeramlug** [comment]
https://developer.apple.com/documentation/foundation/nsurlresponse/1414219-url is the property in question. Separating the structs out for specialization makes sense to me.

**Comment by LoganWright** [comment]
I believe that with the move to using NIO in our client, this issue is no longer relevant. Please reopen if that's not the case 👍

**Comment by vzsg** [comment]
Well, the client is not using NIO at the moment 🤔

**Comment by wlisac** [comment]
@LoganWright I'm also a bit confused – it seems like the client isn't using NIO currently?
