### ISSUE TITLE
Update API docs

### ISSUE THREAD

**Issue by grundoon** [vapor/vapor#1827]
Looks like the API documentation has not been regenerated since 3.0.2, as the `maxBodySize` value typo is still present here:

https://api.vapor.codes/vapor/latest/Vapor/Structs/NIOServerConfig.html#/s:5Vapor15NIOServerConfigV7defaultACSS8hostname_Si4portSi7backlogSi11workerCountSi11maxBodySizeSb12reuseAddressSb10tcpNoDelaytFZ

**Comment by mcdappdev** [comment]
On a side note, I’d love to try and find a way to hook this into the CI process or something. The more things like this we can automate the easier life will be.

**Comment by grundoon** [comment]
Now that I've taken the time to look at a few more repos, it looks to be universal: `latest` is not actually latest release in any of the ones I checked (the links to GitHub source are all to prior release blobs, though at least usually latest minors).

**Comment by tanner0101** [comment]
Currently the API docs are generated locally, then the compiled HTML is pushed to the deploy server. I'd love to update it so that the HTML is generated during the deployment, but I'm not sure it's possible since the generation relies on SourceKitten and Jazzy. I know SourceKitten has been ported to Linux, but I'm not sure if it has all of the required features.

Basically, I just need to spend a couple of hours trying to get the generation script running on Linux. If it indeed works, then I just need to conjure up a Dockerfile that can pull the necessary repos and compile the docs during deployment. We could even get fancy and use GitHub APIs to automatically compile docs for the latest `n` releases.

**Comment by mcdappdev** [comment]
Ah, I didn't realize it relied on SourceKitten. But yeah if there's a way to get it to run on Linux it should be fairly trivial to implement the rest. Would be super cool to use the new Github stuff for it.

**Comment by 0xTim** [comment]
(You could put it on a Mac node on CircleCI or Travis if it’s open source. Guess it depends on being able to hide the secrets

**Comment by joscdk** [comment]
Looks like some work are being done to get Jazzy to work on Linux https://github.com/realm/jazzy/issues/495

After that, with the new API and custom docker, it should be fairly simple to get up on Cloud 2 with something automated :)

**Comment by calebkleveter** [comment]
It looks like you can use Jazzy on Linux since the packages are built with SPM: https://github.com/realm/jazzy/issues/487#issuecomment-361415359

**Comment by Joannis** [comment]
Closing this, because the docs are automatically regenerated nowadays.
