### ISSUE TITLE
Member 'psql' in 'DatabaseIdentifier<_>' produces result of type 'DatabaseIdentifier<PostgreSQLDatabase>', but context expects 'DatabaseIdentifier<_>'

### ISSUE THREAD

**Issue by kevinrenskers** [vapor/vapor#1935]
I'm trying to do some manual queries using the docs on https://docs.vapor.codes/3.0/sql/overview/, but I am not able to get a connection. Always compiler error: `Member 'psql' in 'DatabaseIdentifier<_>' produces result of type 'DatabaseIdentifier<PostgreSQLDatabase>', but context expects 'DatabaseIdentifier<_>'`.

![Screen Shot 2019-03-24 at 17 53 24](https://user-images.githubusercontent.com/229384/54882989-764b8b00-4e60-11e9-873f-f0f33f7c56cc.png)

I already looked at https://github.com/vapor/vapor/issues/1555 which talked about the same error, but the workaround proposed there didn't make any difference.

**Comment by kevinrenskers** [comment]
Never mind, got it to work in the end

**Comment by roisg** [comment]
Hi @kevinrenskers , can you explain what was the issue? I'm facing the same error right now and can't figure it out.

**Comment by kevinrenskers** [comment]
I honestly don't know anymore, but in the end I used `Model.query(on: req).join(..)` instead anyway.

**Comment by 0xTim** [comment]
@roisg it's a really helpful error that basically means you're closure is invalid. If you try and provide a return type to the closure you should get a better error message

**Comment by HashedViking** [comment]
Recently I had a problem with this
`req.transaction(on: .psql) { conn in
                    return try self.makeTransaction(field1: someString1, field2: someString2, req: conn)
                }`
with helper function 
`func makeUserTransaction(field1: String, field2: String?, req: Request) throws -> Future<SomeResult> {}`
So the problem was simply that `conn` has a type `DatabaseConnectable` and not `Request` so expected compiler error message would be `Cannot convert value of type 'DatabaseConnectable' to expected argument type 'Request'` but instead it was that crazy garbage message. Also passing to `field1` or `field2` not a string produces expected `Cannot convert` message. So check everything manually inside your closure, compile it inside your brain.
