### ISSUE TITLE
Feature request: Add an extension that conforms `HTTP.HTTPClient` to `Vapor.Client`

### ISSUE THREAD

**Issue by MrMage** [vapor/vapor#1942]
`Vapor.Client` returns `Response` types, which are more convenient to work with than `HTTPResponse`. Currently `Vapor.Client` is only implemented by https://github.com/vapor/vapor/blob/master/Sources/Vapor/Client/FoundationClient.swift. It would be nice to have an extension that conforms `HTTP.HTTPClient` to `Vapor.Client` to obtain all those conveniences.

**Comment by tanner0101** [comment]
@MrMage `HTTPClient` as implemented in Vapor 3 was more of a proof of concept. There was a lot of work that needed to be done in terms of testing and features--that's why we only offered `FoundationClient`. 

That work has been done in Vapor 4, and now going forward `HTTPClient` will conform: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Client/Client.swift#L5
