### ISSUE TITLE
High cpu usage and not accepted requests

### ISSUE THREAD

**Issue by AnyCPU** [vapor/vapor#1963]
I got the same error message (https://github.com/vapor/vapor/issues/1883) and noticed that the ToDo example may not accept incoming requests, but it may use ~100% cpu core. 

The message:
>[ DEBUG ] Conform `IOError` to `Debuggable` for better debug info. (NIOServer.swift:104)
[ ERROR ] read(descriptor:pointer:size:) failed: Connection reset by peer (errno: 54) (NIOServer.swift:104)

### Steps to reproduce

- turn on your Mac 
- install the Vapor
- build an example - the ToDo
- run the wrk tool: `wrk -c 1000 -d 15s -t 4 http://localhost:8080`

### Expected behavior

If there are no incoming requests, the Vapor should not load CPU

### Actual behavior

the Vapor utilizes ~100% of a one core and does not accept new incoming requests

### Environment

- macOS 10.14.4
- Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
- Vapor Toolbox: 3.1.10

>vapor --version
Vapor Toolbox: 3.1.10
In order to find the Vapor Framework version of your project, it needs to be built at least once
Would you like to build now?
y/n> y
Building Project [Done]
Error: GeneralError(message: "Unable to locate vapor dependency")

**Comment by AnyCPU** [comment]
I understand that this can be not related to the Vapor, but maybe some workaround exists.

**Comment by AnyCPU** [comment]
It seems it is not usable for a project under load.

**Comment by weissi** [comment]
@AnyCPU btw, this error `[ ERROR ] read(descriptor:pointer:size:) failed: Connection reset by peer (errno: 54) (NIOServer.swift:104)` is pretty normal, it just means that the HTTP client has closed the connection when Vapor tried to write a response. Don't know why Vapor has that down as an `ERROR`.

Regarding the CPU load: Are you running in debug or release mode?

**Comment by AnyCPU** [comment]
@weissi it happens in release mode. After running the wrk, it consumes 100% cpu and makes fans noisy.

To reproduce the hello world example and simple Package.swift with Vapor 3.3.0 as dependency can help.

**Comment by AnyCPU** [comment]
@weissi @tanner0101 Hi! Any updates on it?

**Comment by ludmiloff** [comment]
Still same with Vapor 3.3.1 - both in release and debug mode after running a wrk test. No crashes, just 4-5 annoying messages like this:
```read(descriptor:pointer:size:) failed: Connection reset by peer (errno: 54) (NIOServer.swift:104)```

and only 10 connections - ```c 10```
Is it safe to ignore this in production?

**Comment by danieleftodi** [comment]
I'm been testing on macOS Mojave and Ubuntu 18.04 ... and I get the same error, on both systems.

`
[ ERROR ] read(descriptor:pointer:size:) failed: Connection reset by peer (errno: 104) (NIOServer.swift:104)
`

I also have to agree with @weissi, as I notice this "error" only when close our iOS App on the iPhone (double-click-home-button, and swipe up to "kill -9" the iOS App) ... 

If you are running a "Client" (iOS) <--> "Server" (macOS or Linux), setup as we do ... I do know there is a function in AppDelegate of the iOS App to "gracefully" allow it to do some "clean up stuff" before the system (iOS) terminates your App ... like close the socket to the server (Vapor) ... instead of leaving it "open" ... since the server (Vapor) doesn't know that the client (iOS App) has closed ... and the server in its "keep-alive"-loop later finds out that the client "has left the building" 

... ergo we get this ERROR ... "failed: Connection reset by peer" ...

**Comment by bellots** [comment]
I'm getting the same error
