### ISSUE TITLE
Could not build Objective-C module 'CNIOZlib'

### ISSUE THREAD

**Issue by nbhhcty** [vapor/vapor#1976]
In terminal is OK! But in xcode build error.

### Steps to reproduce
1、vapor new HelloWorld
2、cd HelloWorld
3、vapor build
4、vapor xcode
5、open project in xcode

### Expected behavior
Successful run like in the terminal

### Actual behavior
terminal is OK
![image](https://user-images.githubusercontent.com/11188644/57612934-573bc080-75a8-11e9-92cc-7009e5f1df2c.png)

xcode build error
![image](https://user-images.githubusercontent.com/11188644/57612444-6f5f1000-75a7-11e9-9eed-9177c103fee8.png)

### Environment

* Vapor Framework version: 3.0.0
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.4

**Comment by Joannis** [comment]
It's barely out of the printscreen, but what target device is selected in your Xcode project?

**Comment by jonasmunk** [comment]
I have the same issue. In my case the problem is pkg-config from MacPorts pointing at another zlib version. See: https://github.com/apple/swift-nio-zlib-support/issues/2

It looks like you are including zlib from homebrew.

It would be great if this could "just work" - meaning the tool finds and includes (and verifies) the correct version.

I have not been able to get Vapor to build inside XCode.

**Comment by madibb** [comment]
I had the same issue. I managed to build the XCode project by commenting out the line 
`.package(url: "https://github.com/apple/swift-nio-zlib-support.git", from: "1.0.0"),` in `swift-nio/Package.swift`.
After that I ran 
`swift build && swift package generate-xcodeproj`
and then rebuilt the Xcode project - this time successfully.

**Comment by 0xTim** [comment]
MacPorts has caused all kinds of issues with Vapor projects and NIO and (currently) seems incompatible 😕
