### ISSUE TITLE
Support disabling ApplicationResponder metrics

### ISSUE THREAD

**Issue by Firehed** [vapor/vapor#2171]
The recently-added metrics in [ApplicationResponder](https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/ApplicationResponder.swift#L80-L95), while very well-intended, have the potential to conflict with internal metrics and potentially drive up costs to run sites using Vapor when using SaaS metrics providers (which can charge per metric or per dimension emitted).

It would be great if there was a way to make them optional. Currently, it's hardcoded in such a way that the only way (as far as I can tell) to not record/emit them would be to do some very messy patching by looking for known metric names.

I think a superior solution would be to pull the metrics out into their own `Middleware`, and update the templates to use that middleware by default. This would make it very easy for developers to exclude them if they so desire. It does have the minor downside that if the metrics middleware isn't the first one `use`d the timing can be slightly off, but that seems like a typically low-impact concern which can be noted in documentation.

If you like this option, I'm happy to put together a PR to implement it, and I'm open to alternative ideas if you have any.

### Steps to reproduce

Initialize `MetricsSystem` during the bootstrapping process, e.g.
```swift
import Metrics
import StatsdClient
import Vapor
public func app(_ environment: Environment) throws -> Application {
  let statsdClient = try StatsdClient(host: "127.0.0.1", port: 8125)
  MetricsSystem.bootstrap(statsdClient)
  // ...
  return app
}
```
Observe that metrics will be emitted on every request (this may vary slightly depending on the metrics provider)

### Expected behavior

Framework metrics are optional

### Actual behavior

Framework metrics will always be sent if the MetricsSystem has been bootstrapped.

### Environment

* Vapor Framework version: 4.0.0-beta.3.10

**Comment by mcdappdev** [comment]
I agree, I fought for this when the metrics were being added to the framework and lost :( (unless there is an implemented way to turn them off in which case I am happy)

**Comment by MrLotU** [comment]
The simple way to disable application metrics is to not boot the MetricsSystem. Any other issue you're running into is a metrics backend implementation detail. The thought behind swift-metrics is that you can plug in a backend of your choosing and you automatically get all metrics. If you don't plug in anything, there is very little to no loss of time or resources. The way swift-metrics is setup in Vapor is so that it will not interfere with the normal operation of your application.

If you only want a subset of the metrics to be emitted, I advice you to either create your own metrics backend that can do this filtering, or see if it can be PRed into an existing backend of your choice. This is not an issue with Vapor, as you will run into this with every package emitting metrics using swift-metrics.

**Comment by mcdappdev** [comment]
Ah right, yup that makes sense.

**Comment by t089** [comment]
Actually, I disagree. Yes a backend implementation could provide hooks to filter metrics, but how do I know what kind of metrics vapor emits? But what if I have two vapor apps in my binary but I only need metrics from one, how can I disable the other?

 I think the op‘s request makes total sense, as a user of vapor it should be my choice wether I want an instance of vapor to emit metrics or not.

**Comment by MrLotU** [comment]
I can see where you're coming from here, but this is not an issue that's limited to Vapor, but applies to swift-metrics as a whole. If this is something you're after, I would suggest opening an issue over at https://github.com/apple/swift-metrics to open up a discussion on how to achieve this.

**Comment by t089** [comment]
I not sure I understand. My understanding was the following: If I don’t want metrics on every request, then I should not emit metrics on every request. The purpose of the metrics backend is to collect / store / dispatch emitted metrics. It is not the responsibility of the backend to decide what is emitted, this is the job of the application. And at the current state, vapor always emits everything without any configuration option.

**Comment by t089** [comment]
Note also that by definition, the metrics backend has no domain knowledge about the application. It is purely concerned with its basic metrics model. It cannot decide what to process (other than some hard limits like not more than x bytes per label or y metrics per second)

**Comment by t089** [comment]
Please take a look at Spring Boot metrics as an example: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-spring-mvc

The system is very similar to swift-metrics. The app emits metrics, but how these are processed depends on the loaded backend impl. And still, there is a lot of customization possible in Spring itself on how it emits or doesn’t emit metrics. You can even customize the naming and the labels. Would make a lot of sense for vapor as well.

**Comment by tdotclare** [comment]
Temporary solution is just to roll your own Responder and override the default one.

Was going to do something like that myself for things the default responder can’t easily handle, like branching on route paths based on requested domain name.

A more general solution specifically for metrics though would probably be to just attach an optional flag for metrics on Requests, so route handlers/groups themselves can decide whether to report.

**Comment by Firehed** [comment]
> Temporary solution is just to roll your own Responder and override the default one.

I tried this before even posting the issue. Since the responder is a readonly property of the application, it's not possible to replace  (or I can't figure out how - if you do please let me know!)

As it stands I'm now prevented from updating due to this, and given how awful SwiftPM seems to be at selective package updates I'm increasingly inclined to drop Vapor entirely and just deal with the official Apple packages it now uses directly.

**Comment by tdotclare** [comment]
Oh, I just meant modify the package files as necessary for your own build purposes - definitely not ideal since you need to track those changes and repply when updating to newer packages.

I do think the solution is not necessarily anything metric-specific though - making the app responder a configurable option that defaults to the native package ApplicationResponder would be best, IMO... works fine for 99% of cases but is easily replaced when necessary.

**Comment by tanner0101** [comment]
I see a couple of distinct issues here:

1: Vapor is missing the ability to inject a custom `Responder`. 
2: There is no way to disable `ApplicationResponder`'s usage of metrics. 

Both of these make sense to add IMO. 

Regarding 2 specifically, IIRC the reason we didn't implement metrics as a middleware is that we wanted them to be on-by-default with as little performance overhead as possible. Middleware impacts performance. However, for cases where performance is critical, you could just remove all middleware (including the ErrorMiddleware) and that would be even better than what we have now. So unless I'm forgetting something (which I very well could be) maybe we should revisit metrics being a middleware. If there is some reason this really should not be a middleware, then maybe we consider adding an easy way to disable metrics on a per app basis. Something like `app.server.reportMetrics = false`.

**Comment by tdotclare** [comment]
1) I give big **+1** for injecting a custom responder as I think it's the simplest way to handle routing for a lot of things where someone (e.g. me) is using Vapor as closer to a general purpose server and wants to implement pre-route handling behavior (e.g., switching on requested domain name for multiple routing trees)

2) I don't think metric reporting should be broken into middleware since, as you say, performance is improved by having it directly in the responder - I do think being able to control metric behavior per-route/route-group is perhaps more desirable than just a global default though.

**Comment by tanner0101** [comment]
> I give big +1 for injecting a custom responder
Cool +1, do you want to open an issue for that one?
