### ISSUE TITLE
Incremental builds inside Docker

### ISSUE THREAD

**Issue by nugmanoff** [vapor/vapor#2325]
Every time docker container is run and fetches all of the dependencies (vapor, swiftnio & etc) and rebuilds them from scratch. It takes quite a long time. Is there anyway to get incremental builds working inside Docker containers? 

Maybe there is some best practice or workaround I am missing here?

[Related thread on Swift forum](https://forums.swift.org/t/incremental-builds-with-swift-package-manager-and-linux-docker/26538)

**Comment by jonny7** [comment]
This is more so a question for discord rather than an issue with Vapor

**Comment by tanner0101** [comment]
@nugmanoff no it's not possible to do incremental builds in docker because each time docker containers boot all of the files in the filesystem get new `inode` values. This makes the Swift compiler (specifically lldb-build) think they have all been modified. I've asked the Swift team about fixing this and they seem hesitant to do so. That was a while ago though. It's probably worth starting a new conversation on the forums.

**Comment by pazaan** [comment]
This appears to work fine if you [use this suggestion](https://forums.swift.org/t/incremental-builds-with-swift-package-manager-and-linux-docker/26538/20) from the afore-linked forum topic.

**Comment by maerki** [comment]
Has anybody been successful with the argument `--mount=type=cache,target=/build/.build` using GitHub actions? I manage to get incremental builds using docker locally, but still see every file getting recompiled on GitHub action builds.

**Comment by WilliamFernsV3** [comment]
> Has anybody been successful with the argument `--mount=type=cache,target=/build/.build` using GitHub actions? I manage to get incremental builds using docker locally, but still see every file getting recompiled on GitHub action builds.

You can try setting up a self hosted runner that is persistent across multiple runs. Thus, it will have access to the build.
