### ISSUE TITLE
Is it possible embed Vapor in GUI Application?

### ISSUE THREAD

**Issue by diuming** [vapor/vapor#2345]
Vapor Framework version: 4.5.0
Vapor Toolbox version: none(manual)
OS version: macOS 10.15.4

As title.
I want to compile `vapor` once and run everywhere.(portable to other mac machine)
ex: embed `Public`, `Views` and more in Resources folder of GUI Application.

**Comment by Joannis** [comment]
@diuming yes, you can use Vapor from a macOS or Linux app perfectly fine. You will need to make sure that you treat your threads properly. Vapor reply to a request from a different EventLoop than is provided by the Request. And you cannot call your UI from a Vapor thread, because it's not the main thread.

**Comment by diuming** [comment]
So, I need to new a thread and run vapor in it, right?
Could you give me a simple example?
