### ISSUE TITLE
SQL: Can't see the inserted ID

### ISSUE THREAD

**Issue by milosmns** [vapor/vapor#2398]
I'm trying to insert a model into the DB, and return the inserted ID. 
Once inserted (this works ok), `run()` doesn't provide an ID.

### Steps to reproduce

Once I get a connection object from the incoming request, I can execute something like this:

```swift
try connection
    .insert(into: Account.self)
    .value(accountObjectHere)
    .run()
```

Running that gives me `Void`, so I can't really see what I just inserted. 

### Expected behavior

Ideally, `run()` would return either the created model or the new ID. This is what would happen with any other persistence framework... 
But I'll settle for a workaround as well.

### Environment

I'm using this approach: https://docs.vapor.codes/3.0/sql/overview/

* Vapor Framework version: 3.0.0
* MySQL Kit version: 3.3.1
* Vapor Toolbox version: Vapor Toolbox: 3.1.10
* OS version: macOS 10.15.04 & Ubuntu 18.04

**Comment by milosmns** [comment]
Also, unless you're able to give me a fully working Docker image that builds the project, runs its tests and starts the service with Ubuntu 18.04 or newer -- no, I can't upgrade to Vapor 4.

**Comment by gwynne** [comment]
Since you're using MySQL, you can retrieve the ID of the new model with something like:
```swift
/// Add `import MySQL` at the top of the source file

connection
    .insert(into: Account.self)
    .value(accountObjectHere)
    .run()
    .flatMap { (connection as? MySQLConnection)?.lastMetadata?.lastInsertId(as: Account.ID.self) }
    // If `Account` is not a Fluent `Model`, replace `Account.ID` with the appropriate type.
```
From there, unwrap the optional result value. You can use the ID to retrieve the model back from the database, or just set `accountObjectHere.fluentIdD = theNewIdHere`, etc.

However, if your `Account` type is a `Model` in the Fluent sense (and not just something `Encodable`), you can simplify this significantly by just writing `return accountObjectHere.save(on: connection)` - Fluent 3 returns the model as the future result. It's unusual to use the `SQL` layer directly, as you appear to be doing. `SQL` acts as part of the interface between the Fluent ORM and the database drivers; it is not in itself a "persistence framework", which is why it doesn't conform to your expectation in this regard.

(Note: While Fluent 4 does change around the way this is handled, it is not necessary in either 3 or 4 to drop down to the database driver to ask for a generated model ID. It's only necessary here because you're using SQL directly. I always recommend users update to Vapor 4 (and thus Fluent 4 etc.) if they can, but that isn't really the answer to your question as such anyway.)

Last, but not least, the Vapor 4 project template (as cloned by `vapor-beta new MyShinyService`) comes with a fully functioning `Dockerfile` and `docker-compose.yml` configuration. A freshly created project can immediately `docker-compose up -d db && sleep 1 && docker-compose up migrate && docker-compose up app` and be presented with a ready and working service on port 8080, backed by Ubuntu 18.04. (The annoying `sleep 1` bit is an unfortunate workaround for limitations of Docker Compose with respect to dependencies.) The default setup will not run tests as well, but it can be made to do so by adding this line directly above the `RUN swift build...` line in the `Dockerfile`: `RUN swift test --enable-test-discovery --sanitize=thread`. (This will result in the app being built twice, though - once in debug config for the tests, then again in release config for execution. This is also easily changed with a tiny and obvious `Dockerfile` edit.)
