### ISSUE TITLE
Missing value error does not respect the keyDecodingStrategy to show the key name

### ISSUE THREAD

**Issue by jdanthinne** [vapor/vapor#2408]
### Steps to reproduce

Given an input Content like
```swift
class PostInput: Content {
  let id: UUID?
  let title: String
  let isFree: Bool
}
```
the json like
```swift
let decoder = JSONDecoder()
decoder.keyDecodingStrategy = .convertFromSnakeCase
ContentConfiguration.global.use(decoder: decoder, for: .json)
```
and an input like below, missing the isFree value
```json
{
  "title": "The title"
}
```

### Expected behavior

Get an error response like this, mentioning the missing key is **is_free** (because this is what the API is trying to decode).
```json
{
    "error": true,
    "reason": "Value required for key 'is_free'."
}
```

### Actual behavior

Get an error response like this, mentioning the original **isFree** variable key name.
```json
{
    "error": true,
    "reason": "Value required for key 'isFree'."
}
```

### Environment

* Vapor Framework version: 4.10.0
* Vapor Toolbox version: 18.0
* OS version: 10.5.5

**Comment by 0xTim** [comment]
Closing in favour of https://github.com/vapor/fluent-kit/issues/331

**Comment by tanner0101** [comment]
The code above (just using `Content` and a codable struct) _should_ work. However, this will not work with a `Model`. As @0xTim points out, see https://github.com/vapor/fluent-kit/issues/331 for more information on that.

**Comment by jdanthinne** [comment]
I'm already using `Content` DTOs, but this doesn't resolve the wrong error message.

**Comment by tanner0101** [comment]
Ah sorry @jdanthinne I misread the issue initially. I just dug into this to see what's going on. 

It looks like the only place Foundation is giving us the converted key is in the `debugDescription`. This is the structure of the error being returned:

```swift
DecodingError.keyNotFound(
    CodingKeys(stringValue: "isFree", intValue: nil), 
    Swift.DecodingError.Context(
        codingPath: [], 
        debugDescription: "No value associated with key CodingKeys(stringValue: \"isFree\", intValue: nil) (\"isFree\"), converted to is_free.", 
        underlyingError: nil
    )
)
```

This doesn't give us any good options for delivering the key in the abort error. The `debugDescription` is not usable since it mentions the `CodingKeys` struct which would be weird as an API response. It also mentions the key being converted which is an implementation detail and would be confusing. 

That leaves us with two options both of which are prone to breaking easily:

1: Extract the converted key from the string. 

This would make sure we get the correct key, but could very easily break if the format of the error ever changes. 

2: Detect "converted" in the string and apply snake_case automatically.

This would be more resilient to changes in the error message structure, but would not work for custom key conversions. 

I don't think either of these are solid enough solutions to be considered so I'm re-closing this issue.

I've opened [SR-13309](https://bugs.swift.org/browse/SR-13309) to request better error reporting from JSONDecoder. Until then, I think the best option is to use manually defined `CodingKeys`. Not only do these yield the correct error message, they are also much more performant. 

```swift
struct PostInput: Content {
    enum CodingKeys: String, CodingKey {
        case id, title, isFree = "is_free"
    }
    let id: UUID?
    let title: String
    let isFree: Bool
}
```

**Comment by jdanthinne** [comment]
Thanks. I wasn't aware of the performance cost of the global setting vs. `CodingKey`, good to know.
