### ISSUE TITLE
[Proposal] Load the generic .env file first, then a more specific one and with overwrite values

### ISSUE THREAD

**Issue by GildedHonour** [vapor/vapor#2469]
Currently vapor loads a specific .env file, and then the generic one:

https://github.com/vapor/vapor/blob/master/Sources/Vapor/Application.swift#L92

I think that it should be vice versa because it'll make more sense: if a value is specified in the generic file, let's use that. As long there's no key in a more specific .env file, which would then overwrite a value in a generic file. 

In Elixir/Phoenix it's done this way.

When you pass command line arguments, it's the same thing: a default, hardcoded somewhere in Vapor value will be used unless a new value is passed via command line, which will overwritte a default one.

**Comment by tanner0101** [comment]
Hmm the behavior described should be how it works currently. The reason the specific `.env.bane` file is loaded first is because `loadDotEnv` does not overwrite any keys that are already declared. This is what allows for environment variables coming from the command line to have top priority. 

In other words, this is the precedence:

- 1: `export FOO=BAR` from command line.
- 2: `FOO=BAR` in `.env.<specific>`
- 3: `FOO=BAR` in `.env`
