### ISSUE TITLE
XCTVaporTests.setUp should be setUpWithError

### ISSUE THREAD

**Issue by mxcl** [vapor/vapor#2582]
I notice that `XCTVaporTests` implements `setUp` and then has a `try!`.

This should be `setUpWithError` and then losing the bang.

I have not made the PR since maybe you don’t want to do this:

* Possibly `setUpWithError` is newer than the version of XCTest Vapor supports
* Might not be a semantic version major change 
    * Depends if *both* are called
    * There are ordering considerations if both are called
    * OTOH this is testing code so maybe doesn’t matter).

However will PR if ok.

Edit: additionally if we do this `tearDown` should do `app?.shutdown()` since `app` could be `nil` if it throws.

Edit: code reference: https://github.com/vapor/vapor/blob/main/Sources/XCTVapor/XCTVaporTests.swift

Edit: `app` should be set back to `nil` after `shutdown` also really.

**Comment by mxcl** [comment]
I can confirm XCTest calls in following order:

```
setUpWithError
setUp
…
tearDown
tearDownWithError
```

**Comment by 0xTim** [comment]
I'm in favour of this overall. You are correct in the fact that we have to maintain semantic versioning since XCTVapor is part of vapors API. However that doesn't stop us from breaking/fixing behaviour. I'm happy to migrate to `setupWithError` in a PR. We can delete the existing `setup` without breaking SemVer since it will just rely on the superclass. 

As for optionally shutting down the app in teardown in case it throws I'm on the fence. It's probably not a major issue since the test case will have already thrown an error at that point anyway

**Comment by mxcl** [comment]
> As for optionally shutting down the app in teardown in case it throws I'm on the fence. It's probably not a major issue since the test case will have already thrown an error at that point anyway

In fact it crashes since `app` is `nil`.
