### ISSUE TITLE
Validating request body with no fields present

### ISSUE THREAD

**Issue by hsharghi** [vapor/vapor#2606]
### Describe the bug
Using content type `application/x-www-form-urlencoded `, Validating a request body contents for `required` fields, when none of them is present on the the body, validator returns `Abort.422: Unprocessable Entity` error instead of `ValidationError`  

_This issue will not occurs when content type is `application/json`_

### To Reproduce
Create a request content with one field (`email`) and make it `required` in validation rules
 
```
struct ResetPasswordRequest: Content {
    let email: String
}

extension ResetPasswordRequest: Validatable {
    static func validations(_ validations: inout Validations) {
      validations.add("email", as: String.self, is: .email, required: true)    
  }
}
```

send a request to handler without `email` field and try to validate the request content.
```swift
 try ResetPasswordRequest.validate(content: req)
```

Instead of getting `ValidationError` describing that `email` field is `required` you will get `Abort.422: Unprocessable Entity` error.

### Expected behavior

Expected behavior is validator to returns `ValidationError` and identify the missing required fields.
```json
{
  "error": true,
  "reason": "email is required"
}
```

### Environment

* Vapor Framework version: 4.36.0
* Vapor Toolbox version: 18.3.3
* OS version: macOS 10.15.4

**Comment by hsharghi** [comment]
This can't be the expected behavior of the validation module, as it's not the behavior we see in other frameworks.
It it possible to run validation rules on empty container if `request.body.data` was nil?

**Comment by 0xTim** [comment]
Expected behaviour is up for debate because we define how we want our framework to behave. That being said, I think trying to validate the empty body is a reasonable idea and would happily accept a PR! Updating the error thrown to include a reason could be a good intermediate step as well.

In terms of getting it implemented, I'll keep the issue open but not sure when I'll get a chance to implement so will add a 'Good First Issue' label in the hope someone picks it up

**Comment by kareean-star** [comment]
How can it be relevant to have a empty string for validating ?
