### ISSUE TITLE
Support new swift async/await pattern

### ISSUE THREAD

**Issue by benkoska** [vapor/vapor#2638]
Support for the new Swift async/await pattern using actors that was newly announced at WWDC 2021.

Edit: It actually seems as though this pattern was first "released" with swift 5.5 which is still in the beta but swift-nio already supports using the pattern when working with EventLoopFutures so support should be (relatively) straight forward.

**Comment by grundoon** [comment]
(note that there is a pending https://github.com/vapor/vapor/tree/async-await branch in progress)

**Comment by 0xTim** [comment]
You can depend on the branch for now and it should all work 🎉(though might need an update for the latest syntax - if so please raise a new issue). We won't be tagging any releases until Swift 5.5 is officially released as there may be upcoming breaking changes. We also can't release it in an underscored module because we need access to some of the internal stuff in Vapor to offer all the necessary APIs. Hope that explains it!
