### ISSUE TITLE
Add removing invalid space from email and other validation value

### ISSUE THREAD

**Issue by gulivero1773** [vapor/vapor#2656]
<img width="1074" alt="Снимок экрана 2021-07-16 в 09 06 44" src="https://user-images.githubusercontent.com/61082418/125900256-c25cf9f4-ac24-4a57-b6bb-51eed17644b5.png">
![Снимок экрана 2021-07-16 в 09 07 01](https://user-images.githubusercontent.com/61082418/125900279-8d80b8df-9a41-4d80-b5a0-59c3d3a83848.png)
![Снимок экрана 2021-07-16 в 09 07 13](https://user-images.githubusercontent.com/61082418/125900309-843f1193-bde0-41ee-b8a2-f8b91495dfe4.png)
<img width="1044" alt="Снимок экрана 2021-07-16 в 09 07 45" src="https://user-images.githubusercontent.com/61082418/125900364-2ff24232-6fe4-4fdf-9f91-dcf9653b5345.png">

I think we need to add an extension to the validation that will remove whitespace in email and other validations that happen under the hood. Since if the client removes spaces, then there is a small probability that a space in the value will come to the server. I use a validation that happens under the hood and my validation checks the value against the email, but I might get a value with a space from the client. If I comment out the validation, then my function goes further - to check the value

**Comment by gulivero1773** [comment]
![Снимок экрана 2021-07-16 в 09 08 54](https://user-images.githubusercontent.com/61082418/125900447-02e10d7b-7545-4c05-9686-411f189c2cf6.png)

**Comment by 0xTim** [comment]
This is the same as #2651 - this opens up a can of worms that is not the responsibility of Vapor. There are a million and one ways we could tweak the validations - should we also remove any non-alphanumeric characters in the alphanumeric validator etc?

The client is responsible for sending valid data and the validation library is responsible for ensuring the data is correct. If you want this behaviour you'd need to implement it yourself.

(As an aside - getting the validation library to remove any whitespace so that the later decode returns data with no spaces is not possible as the request body is read only. So even if the validation library did this, you could still end up with invalid emails)
