### ISSUE TITLE
deployment documentation

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#267]
Add documentation about how to deploy to Ubuntu
- Supervisor
- Nginx
- Apache
- FastCGI

**Comment by NathanFlurry** [comment]
I really like the graph that Perfect has (here)[http://perfect.org/deployments.html] to outline support to deploying to certain places. I think it'd be a good idea to implement this, since many peoples' main concern is deploying. That said, for pretty much every one of them we'd be telling them to use Docker.

**Comment by johndpope** [comment]
Hi Tanner,
Good job with this project. 

I updated the base swift3 dockerfile to add ssh / could be useful to some.

FROM swiftdocker/swift
https://gist.github.com/johndpope/01a74ffb93921df48e334097117be1b3

from here - one can simply clone a repo (passing a github oauth token)

git clone https://TOKENHERE:github.com/SwiftyBeaver/SBWebsite.git 
vapor build
vapor run serve

and seems to be serving site correctly. thanks again.

**Comment by C0deH4cker** [comment]
@tannernelson: Does Vapor actually support FastCGI?

**Comment by tannernelson** [comment]
@C0deH4cker no, we ended up not adding support since reverse proxying through nginx works well.
