### ISSUE TITLE
Segmentation fault (core dumped),crash

### ISSUE THREAD

**Issue by shenfu1991** [vapor/vapor#2744]
### To Reproduce

1. Add package with configuration '...'
2. Send request with options '...'
3. See error

### Environment

* Vapor Framework version:  4.53.0
* Vapor Toolbox version: 18.3.3
* OS version: ubuntu server 20.04

### Additional context

After running for a few hours, it suddenly crashed

![img](https://wenjian.qianli123.com/error.png)

**Comment by shenfu1991** [comment]
The problem may occur in this method of the routes.swift file
<pre>
   app.get("sendValidation18",":symbol",":res",":its") { req -> AddUserModel in
        let symbol = req.parameters.get("symbol") ?? ""
        let res = req.parameters.get("res") ?? ""
        let its = req.parameters.get("its") ?? ""
        longShortInfo["\(symbol)_\(its)"] = res
        return AddUserModel(msg: "success", success: true)
    }
</pre>

**Comment by mkll** [comment]
What is `longShortInfo`? Is it thread-safe? If it's a regular Swift `Dictionary`, then it's not thread-safe.

**Comment by shenfu1991** [comment]
@mkll yes, longShortInfo is a regular Swift Dictionary,then i try
<pre>
 app.get("sendValidation18",":symbol",":res",":its") { req -> AddUserModel in
        DispatchQueue.global().sync {
            let symbol = req.parameters.get("symbol") ?? ""
            let res = req.parameters.get("res") ?? ""
            let its = req.parameters.get("its") ?? ""
            longShortInfo["\(symbol)_\(its)"] = res
        }
        return AddUserModel(msg: "success", success: true)
    }
</pre>

,It's working fine so far, thanks.

**Comment by mkll** [comment]
@shenfu1991 It will work fine for a while, until the next crash. `DispatchQueue.global()` doesn't help to serialize access because it's a parallel queue, not serial.

And `.sync` blocks your current thread. So you successfully turned your high-performance Swift server app into Django one (maybe it will better to re-write your code in Python?).

Anyway, look at here: https://docs.vapor.codes/4.0/services/#blocking
and here: https://docs.vapor.codes/4.0/async/#locks

**Comment by shenfu1991** [comment]
@mkll thank you very much!
