### ISSUE TITLE
Routing vs subdomains

### ISSUE THREAD

**Issue by bordunosp** [vapor/vapor#2745]
how can I working with multiple subdomains?
don't see it in the documentation..

**Comment by mkll** [comment]
@bordunosp Could you describe the scenario in some details?

**Comment by bordunosp** [comment]
I want to work with 4 domains:
- api.site.com
- doc.site.com
- admin.site.com
- site.com

I want all this to be in one application, without launching 4 different instances, so that they are not pushed among themselves for resources.

Was expecting something like app..grouped by hostname

**Comment by 0xTim** [comment]
@bordunosp Vapor does not provide that functionality out of the box. The easiest way would be to write a custom controller that checks the URL hostname and then calls the correct controller

**Comment by mkll** [comment]
@bordunosp I'm using the same scenario with Vapor and made such a diversification on the front-end Nginx level, because it seems to me that hardcoding the domain names inside the Vapor application is not entirely correct, and I wanted to achieve domain independence at the application level.

This approach fits well with the more general recommendation to use Nginx as a front-end web server to protect the application from incorrect requests, offload SSL, and serve static files - HTML, CSS, images, and others.

I ended up with a fairly complex Nginx config, but it does the job well.

The use of separate controllers for different groups of endpoints, as **0xTim** suggested, is in any case a "must have" for the purpose of dividing the code according to certain criteria. I went a little further and divided the code into modules, with several controllers in each. The only difference is that I split them according to their functionality, not subdomains.

Based on the number of subdomains, it can be assumed that you have a fairly large application. In this case, dividing the code into modules would be very useful.

**Comment by wilapdantop** [comment]
Is there any update on this issue? thank you

**Comment by andreasley** [comment]
I use this custom Middleware to register routes for specific domains:

```swift
import Vapor

// Workaround to be able to specify host-constrained routes in Vapor 4

struct HostBasedRoutingMiddleware : AsyncMiddleware
{
    struct CachedRoute {
        let route: Route
        let responder: Responder
    }

    let hosts: [String]
    let router = TrieRouter(CachedRoute.self)
    let middleware: [Middleware]

    init(for app: Application, hosts: String...) {
        self.hosts = hosts.array
        self.middleware = app.middleware.resolve()
    }
    
    public func register(_ collection: RouteCollection, userInfo:[AnyHashable:Any]? = nil) throws {
        let routes = Routes()
        try collection.boot(routes: routes)

        for route in routes.all {
            // Make a copy of the route to cache middleware chaining.
            if let userInfo {
                route.userInfo.merge(userInfo, uniquingKeysWith: { (first, _) in first })
            }
            let cached = CachedRoute(
                route: route,
                responder: middleware.makeResponder(chainingTo: route.responder)
            )
            
            let path = route.path.filter { component in
                switch component {
                case .constant(let string):
                    return string != ""
                default:
                    return true
                }
            }
            
            router.register(cached, at: [.constant(route.method.string)] + path)
        }
    }

    func respond(to request: Request, chainingTo next: AsyncResponder) async throws -> Response {
        if let host = request.headers[.host].first, hosts.contains(host) {
            let pathComponents = request.url.path.split(separator: "/").map(String.init)
            if let hostSpecificRoute = router.route(path: [request.method.string] + pathComponents, parameters: &request.parameters)?.route {
                request.route = hostSpecificRoute
                return try await hostSpecificRoute.responder.respond(to: request).get()
            }
        }
            
        let response = try await next.respond(to: request)
        return response
    }
}

```

Usage:

```swift
let somehostMiddleware = HostBasedRoutingMiddleware(for: app, hosts: "www.somehost.com", "www.somehost.net:8080")
try somehostMiddleware.register(SomeRouteCollection())
app.middleware.use(somehostMiddleware)
```

**Comment by 0xTim** [comment]
I'm going to close this for now and it's slightly out of scope for Vapor core and better suited to a package containing a custom `Responder` or `Middleware` as shown by @andreasley

**Comment by dimitribouniol** [comment]
Inspired by @andreasley's middleware, I built a full package that allows full routing on domain paths: https://github.com/mochidev/HostRouter
