### ISSUE TITLE
Editing a Package Dependency as a Local Package

### ISSUE THREAD

**Issue by backslash-f** [vapor/vapor#2771]
Should this work with Vapor?

https://developer.apple.com/documentation/swift_packages/editing_a_package_dependency_as_a_local_package

What happens in my environment is: when I drag and drop the directory of a Swift package inside the Vapor project in Xcode, the entire structure of said package is copied inside the Vapor project as if I was adding new source files.

Another way to reproduce: if I create an Xcode project from the Vapor project (`swift package generate-xcodeproj`) and drag and drop the package again, then it will not copy the directory of the Swift package, it creates a reference to it (as expected). However it will not "_override the package dependency with the same name_" as the documentation suggests -- the project will now have two distinct references for the same package: one remote and one local.

Unsure how to proceed... The goal is to be able to edit a package dependency as a local dependency inside the Vapor project as stated in the above link and when I'm done, I would just remove the local reference (and push my package changes).

Please advise, thanks.

Xcode: 13.2.1
Swift: 5.5.2
Swift tools: 5.5
Vapor: 4.54.0

**Comment by 0xTim** [comment]
Yes Vapor works fine. You need to do it in a new workspace otherwise Xcode doesn't like it. I wrote about how to do that here https://www.timc.dev/posts/editing-swift-packages/

Make sure you drag it to the same level as the Swift project you're currently working on, and not at an _inner level_. There's a very subtle difference and the latter will have unintended side effects. Xcode's UI isn't very good in this regard
