### ISSUE TITLE
Running "Build Documentation" doesn't get Xcode to show me the docs

### ISSUE THREAD

**Issue by MrTheSaw** [vapor/vapor#2778]
### Describe the bug

Build Documentation builds the docs, but Xcode continues to tell me to build the docs.

### To Reproduce

10 In my code in the routes function, right click on the class reference "Application".
11 REM _(in routes.swift as provided by the application initializer,_
12 REM _but I get the same thing with other Vapor classes in other files.)_
20 Select "Get Quick Help"
30 In the quick help view, select "Open in Developer Documentation"
40 Get a dialog instructing you to build the documentation.
50 Build it.
60 GOTO 10

### Expected behavior

See the full documentation in the Documentation Window

### What Actually Happens

It keeps looping. It builds the first time, and just quickly rechecks the build in subsequent times, but never shows me the docs or even where I might find the output of whatever just happened.

### Environment

* Vapor Framework version: 4.55.0
* Vapor Toolbox version: 18.3.3
* Xcode: Version 13.2.1 (13C100)
* OS version: 12.1 (21C52)

### Additional context
I have raised the OS deployment version in the Package File to .v12, the app seems to run fine, FWIW.

**Comment by 0xTim** [comment]
Vapor does not currently use or support DocC which is why there's nothing to build. We use `swift-doc` to generate API docs (https://api.vapor.codes) and a separate repo for https://docs.vapor.codes/4.0/

Inline docs should be available if you option-click methods.

The Xcode looping is a bug in Xcode from the sounds of it
