### ISSUE TITLE
does vapor 4 redis api now support async/await?

### ISSUE THREAD

**Issue by absadunn** [vapor/vapor#2858]
`let value = try await app.redis.get("my_key", as: String.self)`

this was written in the vapor 4 redis document(https://docs.vapor.codes/redis/overview/), but I found the "try await" does not work in xcode, it gives a warning "No calls to throwing functions occur within 'try' expression", and the redis.get returns a EventLoopFuture type. It seems like it does not support? Is it true or is there any other  api methods which support redis to use async/await.

**Comment by gohanlon** [comment]
Since you just closed this issue, I take that to mean you solved your issue. But, just in case, or for anyone how may come across this issue:

> It seems like [Vapor] does not support [async/await]?

Vapor does support async/await via a newer style of writing routes, where you handler function is `async`:

``` swift
routes.get("firstUser") { req async throws -> String in
    guard let user = try await User.query(on: req.db).first() else {
        throw Abort(.notFound)
    }
    user.lastAccessed = Date()
    try await user.update(on: req.db)
    return user.name
}
```

Source: https://docs.vapor.codes/basics/async/

I don't know whether the Redis API has an analogous non-async method you could call instead, but it likely does. (I've only used the async Vapor Redis API.)

As you may have already noticed, the default template doesn't use the newer "async/await" style handler functions. Maybe @0xTim can say whether it should?

While it would be very unusual to need to, you could also continue using non-`async` handler methods and use Swift's `Task` API to manually create an async context in order to then call `async` functions (those that you need to `await`). When you declare your function to be `async`, Vapor provides the async context (so it can call your function).

The Swift Concurrency WWDC sessions from  [WWDC21](https://developer.apple.com/videos/wwdc2021/?q=concurrency) and [WWDC22](https://developer.apple.com/wwdc22/sessions/?q=concurrency) may interest you, too. Cheers!

**Comment by 0xTim** [comment]
The template was updated for async/await a while ago - https://github.com/vapor/template/pull/56

**Comment by gohanlon** [comment]
Ah, I was only considering the ["bare" template](https://github.com/vapor/template-bare), and using the non-`async` style makes sense to given how trivial "hello world" is.

**Comment by qq1440214507** [comment]
this way can work
` _ = try await req.redis.set(.smsCode(phone), to: smsCode,onCondition: .none,expiration: .seconds(300)).get()`
