### ISSUE TITLE
Cannot deploy on AWS EC2 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by gabrielcosi** [vapor/vapor#2899]
### Describe the bug

I can't start the server neither in debug mode nor in production, according to the documentation at https://docs.vapor.codes/deploy/digital-ocean/ sudo .build/release/Run serve should start the server but the folders I have are different. At the end I got ```sudo: .build/release/Run: command not found```

### Expected behavior

Server started

### Environment

* Vapor Framework version: 4.0
* OS version: Ubuntu 20.04 LTS
* Swift version: 5.7
* Swift target: x86_64-unknown-linux-gnu

### Additional context
Even finding the directory in .build/x86_64-unknown-linux-gnu/release/Run, anyway ```sudo: .build/x86_64-unknown-linux-gnu/release/Run: command not found```

<img width="850" alt="image" src="https://user-images.githubusercontent.com/44176694/195873181-baccfff2-d6fe-4a6b-beb3-26629538771b.png">

**Comment by vzsg** [comment]
It's more than likely that your build failed, which is why the Run executable was not created. Usually it ends with a "Killed" message, signifying the OOM, but sometimes you just get the shell back.

That happens very often with undersized droplets (you should use at least 4 GB of RAM **and [swap](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04)** for building a Vapor app).

**Comment by 0xTim** [comment]
Closing this as it's likely a memory issue - feel free to reopen if the above advice doesn't solve it

**Comment by mkll** [comment]
@vzsg 
> You should use at least 4 GB of RAM and for building a Vapor app.

Well, I successfully use a 2GB RAM machine to build.
