### ISSUE TITLE
Need interactive overview on Vapor

### ISSUE THREAD

**Issue by proyb6** [vapor/vapor#292]
As an inexperienced Swift programmer, I would like to learn Vapor internal structure 1st to the end in detail or less jargon.

Jeffery at LaraCast did explained the internal functions in Symfony but that is not useful if the features change over time.

If we want to attract inexperience/different programmers background to adopt Vapor swiftly and low barrier, a less jargon is easier to remember and less bugs when contribute to improving Vapor. I dislike all PHP frameworks that are complexity that majority of the programmers are limited to being a "content builder" and not a "contributor" that can't help much except filing bugs.

**Comment by LoganWright** [comment]
Great suggestion @proyb6. Making Vapor and inclusive and accessible framework is important. Beyond beginners, this could be a good way for potential contributors to get an idea of how things work when jumping into the codebase. 

One thing I'd like to say on this is that given the rapidly changing development environment right now, I'm partial to waiting until we get at least a 1.0.0 stamp so that the documentation will last at least to some degree.

Would you mind adding some links to this thread to other examples that you thought were well done that we could model off of.

**Comment by proyb6** [comment]
Nice artworks for visual made by Total designer
https://www.toptal.com/software/introduction-to-concurrent-programming
vs
http://www.integralist.co.uk/posts/concurrency.html#3
Animation may be use to get the idea how the data move and I think it can be taxing to learn coding for some busy professional in IT and non-IT will welcome interactive animation.

Get the big picture. Source code in visualisation and ability to lookup each APIs and auto display their dependencies without looking linear code in Xcode, great for use in your presentation as good as virtual reality
https://www.youtube.com/watch?v=MR4_5GSID2A
vs
https://laracasts.com/series/whats-new-in-laravel-5-1/episodes/15
LaraCast behind the screen.
The busy profession in IT and non-IT will find it easier to adapt and get it swiftly, well, satellites made that possible for gathering real world data and traffic.

**Comment by tannernelson** [comment]
http://docs.vapor.codes is a great overview of Vapor and we will be releasing videos once we hit 1.0.
