### ISSUE TITLE
how to set http/https proxy

### ISSUE THREAD

**Issue by shenfu1991** [vapor/vapor#2941]
### Describe the bug

I want to make a network request with http/https  proxy, like <pre>
         let proxyHost = 127.0.0.1
         let proxyPort = 8888
           let url  = request url
           let res = app.client.get("\(url)").flatMapThrowing { res in
                try res.content.decode([PriceModel].self)
            }
</pre>

but I don't know how to do it, I can't find the relevant setting method on the document, please help me, thank you very much

### Environment

* Vapor Framework version: 4.65.2
* Vapor Toolbox version: main (6000cc5)
* OS version: ubuntu 20.04

**Comment by mkll** [comment]
@shenfu1991 HI! Just look here: https://swift-server.github.io/async-http-client/docs/current/AsyncHTTPClient/Classes/HTTPClient/Configuration/Proxy.html

P.S. Let me follow up with an interest, why did you assign the label "bug"? After all, even if the functionality you need did not exist, it would not be a bug, it's just a lack of functionality. A "bug" can only be functionality that exists but does not work as advertised, isn't it?

**Comment by shenfu1991** [comment]
@mkll 
Thanks for providing the documentation, but I tried to follow the documentation and it didn't work. Can you give me a specific example?

<pre>
let proxy = HTTPClient.Configuration.Proxy.socksServer(host: "http://127.0.0.1",port: 1080)
app.http.client.configuration.proxy = proxy
</pre>

**Comment by mkll** [comment]
@shenfu1991
Your code looks correct. Could you please give more detailed explanation of events that lead you to the conclusion that it doesn't work?

**Comment by shenfu1991** [comment]
@mkll 
Hi, in main.swift file, the code is:

<pre>
import App
import Vapor
import NIO
import NIOHTTP1
import NIOSOCKS

var env = try Environment.detect()
try LoggingSystem.bootstrap(from: &env)
let app = Application(env)
app.http.server.configuration.port = 1991


//doesn't work
//let proxy = HTTPClient.Configuration.Proxy.socksServer(host: "http://127.0.0.1", port: 1080)

// set proxy,doesn't work
let proxy = HTTPClient.Configuration.Proxy.server(host: "http://127.0.0.1", port: 1080) 
app.http.client.configuration.proxy = proxy  

defer { app.shutdown() }
try configure(app)
try app.run()
</pre>

and 

<pre>

public func configure(_ app: Application) throws {
      try routes(app)    

   // url request
     var URLString = "server url"
      let res = kApp.client.get("\(URLString)").flatMapThrowing { res in
                try res.content.decode([PriceModel].self)
       }.map { res in
              
       }
}

    
 </pre>



I checked the proxy in ubuntu terminal and it work well.

**Comment by mkll** [comment]
@shenfu1991 Try to replace
`app.client.get("\(URLString)")`
with
`app.http.client.get("\(URLString)")`

**Comment by mkll** [comment]
@shenfu1991 
Follow-up. Vapor is a highly organized and intricately structured application, so it makes sense to follow its conventions and use the appropriate features.

In particular, if you need to execute an outgoing network request when Vapor boots, then you **should not** place a call to this request in `configure()`. There is a special type for this, `LifeCycleHandler`. It guarantees that your request will be executed at the point in time when it is allowed.

Why you should not make a request in `configure()`?

Because at this moment the application has not yet been fully initialized. For example, the database, where you might want to save the result of the request, is not yet ready.

You can read more here:
https://docs.vapor.codes/advanced/services/#lifecycle

_(In general, it's highly recommended to read a whole Vapor documentation to better understand its structure, abilities and features)_.

The `configure()` function is intended to, oddly enough, **configure** the Vapor application, and not to execute some other code for other purposes. Therefore, it makes sense to move here those `HTTPClient` settings that you made in the `main.swift`.

**Comment by shenfu1991** [comment]
@mkll thanks a lot.
