### ISSUE TITLE
String with HTML tags renders plain text

### ISSUE THREAD

**Issue by genericptr** [vapor/vapor#2942]
### Describe the bug

According to https://docs.vapor.codes/leaf/custom-tags/ you should be able to return HTML in LeafData.string but I found it only renders plain text tags from the templating.

### To Reproduce

```swift
public struct MyTag: LeafTag {
    public init() {}

    public func render(_ ctx: LeafContext) throws -> LeafData {
        return .string("<p>hello</p>")
    }
}
```

Including the tag into HTML:

```
#mytag()
```

Will insert a plain text node with the content `<p>hello</p>` instead of `<p>` nodes.

### Expected behavior

Should render `<p>` nodes with text content as you would expect.

### Environment

Safari 16.2
Vapor 4.0.0
macOS 13.1

**Comment by vzsg** [comment]
There's a small Tip box in the documentation that tells you about this behavior and what to do about itÉ

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1783465/214287343-c6e69a94-8e64-4e53-bb6d-e8c5623a0936.png">

In short, instead of LeafTag, you're supposed to use UnsafeUnescapedLeafTag.

---

Unfortunately, the rest of the documentation page seems to not have been updated when [this feature was introduced](https://github.com/vapor/leaf-kit/releases/tag/1.3.0). ☹️
