### ISSUE TITLE
Code does not prompt in Xcode 14.3.1

### ISSUE THREAD

**Issue by Muning69** [vapor/vapor#3027]
Code does not prompt in Xcode 14.3.1

For example, if an error input throw Abort is thrown, Abort will not prompt. There are still many codes that are not prompted.

**Comment by mkll** [comment]
@Muning69 You mean code autocompletion in Xcode?

**Comment by Muning69** [comment]
@mkll 
Code does not prompt.
For example, if you type throw Abo, It should prompt Abort(). But in Xcode 14.3.1, there is no prompt for the built-in type of Vapor.

**Comment by vzsg** [comment]
<img width="877" alt="image" src="https://github.com/vapor/vapor/assets/1783465/b2ec7102-4d25-4809-a453-8bf3748c5eac">

Seems to be working fine here.

**Comment by Muning69** [comment]
@vzsg 
your Xcode is 14.3.1 ?
if Xcode is 14.3 No problem.
if Xcode is 14.3.1 Existing problems.
I have tried cleaning the Xcode cache file, but it still cannot be resolved.

**Comment by mkll** [comment]
@Muning69 Why are we discussing Xcode issues in the Vapor repository?

**Comment by Muning69** [comment]
@mkll 
I'm not sure if this is an Xcode issue or a Vapor issue.

**Comment by Muning69** [comment]
@mkll @vzsg 
![](https://github.com/Muning69/images/blob/main/截屏2023-06-05%2018.43.57.png?raw=true)
![](https://github.com/Muning69/images/blob/main/截屏2023-06-05%2018.46.08.png?raw=true)
![](https://github.com/Muning69/images/blob/main/截屏2023-06-05%2018.48.14.png?raw=true)

**Comment by mkll** [comment]
@Muning69 This issue has been happening since Xcode 13 or even earlier. The weaker your computer and the larger your project, the more likely you are to encounter it.

You say that it is enough to replace Xcode 14.3 with 14.3.1, as the problem arises. The Vapor version remains the same. Why do you think that the cause is Vapor?

P.S. Xcode indexes the source code of the project and after that gets the ability to code completion. In general, neither you, nor I, nor the authors of Vapor can influence this in any way.

**Comment by Muning69** [comment]
@mkll I'm just not sure where the reason lies, I just hope to bring it up and see if it can be resolved. I am still studying Vapor, thank you for your reply.
