### ISSUE TITLE
Proposal on Soft Delete.

### ISSUE THREAD

**Issue by Muning69** [vapor/vapor#3110]
When there are two fields in a record used to record the soft deletion time of two users, but the current soft deletion will simultaneously write these two fields to the same deletion time.

**Comment by mkll** [comment]
@Muning69 What do you mean when you say "deleting two users"? What are the two users?

If you use one record to store some attributes related to two (or more) users, whatever it is, then if this record is deleted, everything stored in it will be deleted.

**Comment by Muning69** [comment]
`tableID | user_a | user_a_deletedAt |  user_b | user_b | user_b_deletedAt`

For example, in the above example, I may want to record the soft deletion time of different users separately in one record.

**Comment by Muning69** [comment]
@mkll 

If user A performs a soft deletion, but user B does not, user B hopes to be able to request the data normally.

**Comment by mkll** [comment]
@Muning69 You cannot delete such a “user” by querying the database, because the database operates on the entire record, and all operations (create, update, delete) are performed on the record. The `deletedAt` field reflects the deletion of the entire record, not part of it.

You can delete, for example, `user A` at the business logic level of your application, but at the database level this will be a record update, not a delete.

If you want to put two users in one record, then all operations on them are the responsibility of your application, not the database. In this case, manipulations with users do not correlate in any way with manipulations with records. Deleting a user is not equivalent to deleting a record, your application logic is completely divorced from the database logic.

Accordingly, since you are building your own logic on top of the database logic, then you should go all the way and not use predefined fields, in particular, `deletedAt`, but provide your own fields of similar purpose, and your own logic for processing them.

P.S. The meaning, purpose and benefits (if any) of this approach are completely unclear. However, it's up to you.

**Comment by Muning69** [comment]
@mkll 
What you said makes sense.
But I think Vapor can do better in this area.
After all, soft deletion is defined by Vapor.
We should be able to come up with a more convenient soft deletion solution in this regard.

**Comment by Muning69** [comment]
@mkll 
What you said makes sense.
But I think Vapor can do better in this area.
After all, soft deletion is defined by Vapor.
We should be able to come up with a more convenient soft deletion solution in this regard.
