### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by wlxo0401** [vapor/vapor#3120]
Can add Privacy Manifest to respond to Apple's changed policy??

Below is Apple's official video of Privacy Manifest.
---
https://developer.apple.com/videos/play/wwdc2023/10060/

**Comment by gwynne** [comment]
Such a manifest is somewhat pointless for Vapor, since it is not primarily intended for use on Apple platforms and there is no code specific to any relevant macOS or iOS APIs or data. The manifest ends up looking like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
</dict>
</plist>
```
I'm willing to add this manifest to the Vapor package, but I'm not clear on whether it would be useful to do so.

@0xTim Any thoughts?

**Comment by wlxo0401** [comment]
@gwynne 

Thank you for your quick response. 

I thought it should be added to all libraries even if you don't use a specific API, isn't it??

**Comment by 0xTim** [comment]
@wlxo0401 you only need to add a manifest if they store user data or are part of a list of popular xcframeworks (https://developer.apple.com/support/third-party-SDK-requirements/)

Since Vapor is neither, you don't need one. If however you receive an email saying you do, please create another issue and we can liaise with DTS to clear it up
