### ISSUE TITLE
How to allow calls to an insecure URL?

### ISSUE THREAD

**Issue by m-revetria** [vapor/vapor#541]
How can I change the HTTP client's configuration to allow invalid certificates?

Currently I'm trying to connect to a locally hosted HTTPS server which has an invalid self-signed TLS certificate. This server only accept HTTPS requests.

I'm getting next error when I make I call to this server:

```
    Making TLS call over Foundation APIs. This will break on Linux. Visit https://github.com/qutheory/vapor-tls
    2016-08-25 11:08:28.407 App[8233:84789] CFNetwork SSLHandshake failed (-9807)
Transport.FoundationStream.Error.unableToCompleteWriteOperation
    Server error: dispatch(HTTP.ParserError.streamEmpty)
```

-----------

Environment:
* Xcode 8 beta 6
* Swift DEVELOPMENT-SNAPSHOT-2016-07-25-a
* Vapor 0.16.2

**Comment by tannernelson** [comment]
This would depend a lot on what type of stream you are using. Looks like Foundation stream here. We are moving to LibreSSL TLS streams in 0.17 so we should see how this looks after the release.

**Comment by tannernelson** [comment]
Could you submit the URL you are trying to call as a failing test to Vapor? That way we can make sure it doesn't get forgotten

**Comment by m-revetria** [comment]
@tannernelson, thanks for your response. 

Here there is more info about my environment that may be useful. I'm running this vapor project in Mac OS X 10.11. From one of my controllers I'm hitting a Xcode Server API hosted in my computer, the URL is https://127.0.0.1:20343/api/bots.

I start the vapor server as following:

```swift
let drop = Droplet(providers: [VaporMustache.Provider.self])
let bots = BotController(droplet: drop)
drop.resource("bots", bots)
drop.serve()
```

Additionally, the controller looks like this:

```swift
import Vapor
import HTTP

class BotController: ResourceRepresentable {
    typealias Item = Bot

    let drop: Droplet
    init(droplet: Droplet) {
        drop = droplet
    }

    func index(request: Request) throws -> ResponseRepresentable {
        let client = try drop.client.make(scheme: "https", host: "127.0.0.1", port: 20343)
        return Response(status: .ok, headers: ["Content-Type": "application/json"]) { [weak self] chunker in
            let botsResponse: Response?
            do {
                botsResponse = try client.get(path: "/api/bots", headers: ["Accept": "application/json"])
                debugPrint(botsResponse)
            } catch {
                botsResponse = nil
                debugPrint(error)
            }

            if let json = try botsResponse?.json?.makeBytes() {
                try chunker.send(json)
            }
            try chunker.close()
        }
    }

    func makeResource() -> Resource<Bot> {
        return Resource(
            index: index
        )
    }
}
```

Meanwhile 0.17 is not released, is there any workaround that I can use?

**Comment by tannernelson** [comment]
Using plaintext (http without ssl) would be the best option for now. You _might_ be able to override the client to use a stream that doesn't verify certificates but that would probably be a headache.

**Comment by czechboy0** [comment]
@tannernelson Xcode Server API doesn't work over HTTP, so that's not an option. I know what @m-revetria is talking about, I've spent quite a [lot](https://github.com/czechboy0/Buildasaur) [of](https://github.com/czechboy0/xcodeserversdk) time working with the XCS API. 

@m-revetria You mention it's an *invalid* self-signed certificate? Are you sure? I know XCS uses self-signed certificates, but they're still valid. You can get around that with the `-k` (insecure) option in `curl` , [this](https://github.com/czechboy0/XcodeServerSDK/blob/1bdcf1af67007123d25e2e73504935c46084bb08/XcodeServerSDK/XcodeServer.swift#L48-L71) is how I got around it using NSURLSession.

Vapor will need an option to disable failing on self-signed certificates, which is a quite often-needed option. I don't know the details of how to achieve that in LibreSSL, however, so I'll have to do the research as well.

**Comment by tannernelson** [comment]
Seems like this will be taken care of in the engine and tls packages. Let's try to get into 0.17 if we can but if not 0.18 for sure. 

Currently dev version of Vapor does not certificate verification at all from the client end since we don't have any certs so @m-revetria's code should work regardless in the next patch.

**Comment by czechboy0** [comment]
@tanner It won't without also disabling hostname verification (see the tls PR where I added that option in TLSConfig). If we get it in then yes.

**Comment by m-revetria** [comment]
@czechboy0 regarding the server's certificate you're right, it is valid, it's just is self-signed. The `-k` option works fine in curl.

I could correctly hit XCS API using URLSession following your suggestion in my Vapor project. It's a momentary solution until a new Vapor release has an option to skip certificate and hostname verification. Thanks for your help

**Comment by czechboy0** [comment]
Yeah the next Vapor should allow self signed certificate. Happy to help!

**Comment by LoganWright** [comment]
Is this now possible in the 0.17 release w/ TLS all setup?

**Comment by tannernelson** [comment]
Yes, it is.
