### ISSUE TITLE
Localization suggestion

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#589]
I suggest looking into Laravels trans function. 

```
/**
     * Get the translation for the given key.
     *
     * @param  string  $key
     * @param  array   $replace
     * @param  string|null  $locale
     * @param  bool  $fallback
     * @return string|array|null
     */
    public function get($key, array $replace = [], $locale = null, $fallback = true)
```

So you have lang as a later param and optional
And the replace array is golden. We need something like that also.

What is your thoughts?

**Comment by Casperhr** [comment]
Also we need a way to do translates without drop instance?

**Comment by NathanFlurry** [comment]
Right now, the `Localization` class is usable without a Droplet. #587 made it a bit easier to use independently.

I've never used Laravel, so I'm not sure what the replace array does. Mind elaborating, since their documentation isn't very explicit? Also, feel free to weigh in on #588, since it seems fairly related.

**Comment by Casperhr** [comment]
The replace array is an easy why to replace words in runtime

Fx
Translate string 
```
"userLikesPost" = "{user} liked your post"
translate("userLikesPost", ["{user}" => "Casper"]) == "Casper liked your post"
```

**Comment by NathanFlurry** [comment]
That's interesting, but I would personally prefer just using [`String(format:arguments:)`](http://swiftdoc.org/v2.2/type/String/#init-format_arguments_). However, that does require the arguments to be in the correct order. Otherwise, I think we should just use [`stringByReplacingOccurrencesOfString(_:withString:options:range:)`](http://swiftdoc.org/v2.2/type/String/#func-stringbyreplacingoccurrencesofstring_withstring_options_range_). Adding that functionally do the localize method itself seems redundant, in my opinion.

**Comment by dlbuckley** [comment]
Just started looking at Vapor and the localisation system is one thing thats struck me as lacking at the moment. Localisation is one of those things that requires a lot of thought to support the vast number of syntactic differences between the languages of the world and as it stands the current system just isn't up to scratch.

Ideally localisation should support:

- Selecting a string based on a key to be used for a given language (this is the current system)
- Positioned value replacements. Not all languages order their syntaxes the same, sometimes values are written in a different order from one language to another.
- Pluralisation support. The difference between using '1 dog' and '2 dogs'. In english this is simple but there are other languages that change for other multiple values (I think there is a language that changes for multiples of 10). (see apples documentation on localising plurals here: https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW10)

I think we can create a revamped system to handle all of this but it needs some thought as to the best approach considering the system that is currently used will have to be migrated or have legacy support. Thoughts?

**Comment by LoganWright** [comment]
Adding this here, relevant to pluralization brought up by @dlbuckley 

http://macoscope.com/blog/effective-localization-when-working-with-language-plural-rules/

**Comment by tanner0101** [comment]
This is going to be implemented as a separate package in the future.
