### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by pjebs** [vapor/vapor#605]
I remember when this was released, the marketing said the aim was to mirror Laravel to some extent?

I'm a Laravel/PHP user but looking for swift.
Is that still the aim.? Or did you remove reference to that for legal/trademark reasons?

**Comment by LoganWright** [comment]
Hi @pjebs 

Laravel is a great framework, and early on, it was definitely an inspiration. Since then, Swift and Vapor itself have begun to take on a life of their own and creating their own conventions.

If you're a Laravel/PHP user, Swift and Vapor should look familiar to get started!

Best,

Logan

**Comment by tannernelson** [comment]
Larave's concision and expressiveness will always be an inspiration to Vapor. But we've gotten plenty of other inspiration since, so not fair to give all the thanks to one framework.
