### ISSUE TITLE
Push Notification for iOS and Web

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#606]
Notification Service Extension is an interesting feature that can send plaintext or rich push notifications to iOS.

Is it available on Linux and macOS server  side beside the pubsub method?

**Comment by NathanFlurry** [comment]
Perfect already implemented this [here](https://github.com/PerfectlySoft/Perfect-Notifications). For now, you could probably fork it to make it work with Vapor, but this would definitely be a good thing to implement for Vapor — especially since a lot of newcomers are iOS developers.

**Comment by LoganWright** [comment]
Hey guys, we'll definitely have more integrated support coming soon. The perfect implementation has way too many dependencies for us to bring in, but there are also a couple examples from our own community of libraries. I can't find them now, once we get 1.0 out, we can dig into this more.

Initial perusing:
https://github.com/alexeyxo/swift-apns

**Comment by a2** [comment]
@LoganWright Was unable to make that work for now 😢

**Comment by Casperhr** [comment]
I suggest using a Push provider

You will discover later on that having logs over push and payloads is super important.
And if you later want to Android support, no changes have to be done to your backend

https://onesignal.com/ is a trending and free option

My companies uses https://www.urbanairship.com/ which is paid.  But there is 15+ options

**Comment by matthijs2704** [comment]
@Casperhr I don't prefer that, I prefer a direct method (APNS/GCM) because of the extra features it provides (Not only push notifications, also downstream messaging, data providing, ect.)

**Comment by Casperhr** [comment]
You have a lot of these feature through the providers also.
But fair.

**Comment by gregpardo** [comment]
I would prefer a default implementation as well as community modules supporting third party providers. Writing an extension for a 3rd party system should be fairly straight forward.

**Comment by LoganWright** [comment]
@gregpardo I think there are some existing mac / ios solutions out there. My initial instinct is that we grab one that kind of works and fork/modify as needed. If they're universal, the author would probably appreciate the PR.

**Comment by Casperhr** [comment]
I really don't understand this.

I know for a fact that non of our competitors or us have direct push notifications integrated in any projects.

You need to have queues running as soon as you get a bit of users. 
So either pick a push provider and setup a dedicated application just for this.

With all push providers, you don't even have to store the device tokens. And users will get notified on all their devices at the same time. Without coding anything!

Imo It's like building a mail/sms server all over

**Comment by matthijs2704** [comment]
@Casperhr I know a lot of companies who like to handle push notifications themselves. True, it'll have queues once you have a bit of users and if necessary everything can run separately in a different app or thread (yey swift! ;P)

I think it's the best to give developers/users a choice ;) If they want to do it themselves, sure let them  and provide a way to do so, otherwise if you think it's too much of a hassle, use a push service. Personally I also like the challenge to do it myself and I don't have to rely on external services. Perfect has a great direct push notification library: https://github.com/PerfectlySoft/Perfect-Notifications

**Comment by Casperhr** [comment]
Ok I get that point. 
But I rather not copy all features Perfect does. Specially if I do not agree on it. I rather want Vapor to a framework we we do few things VERY well, instead of trying to solve every single issue half

**Comment by gregpardo** [comment]
If you rarely send push notifications then using a 3rd party is a dependency that you might not want. A lot of enterprise companies prefer to stay away from 3rd party integration. If you work at a small startup it might make sense though.

**Comment by NathanFlurry** [comment]
No matter what, I personally believe that we should have a native approach without outside services for notifications. @Casperhr If you're concerned about doing a few things very well, then let's just fork or make an adapter for any of these other APNS implementations for Vapor. There's no need to completely rewrite it.

**Comment by Casperhr** [comment]
I think my point is
Sending the push notification through apples api is not really the hard part. There is so much more to it!

If this brings value to some developers fine by me. Just saying I would never recommend using it for any of the projects we build or consult for.

**Comment by NathanFlurry** [comment]
@Casperhr Mind elaborating on the reason you wouldn't use it for your projects? Is it just because Urban Airship (or whatever the cool kids use now and days) is more heavily stress tested and better supported?

**Comment by Casperhr** [comment]
@NathanFlurry 

Urban airship is not really the cool kid in the block, it's more enterprise without being Azure :)

Onesignal is the cool kid and free!

So if you decide to do push from scratch. You need to deal with following which you don't need with a pusher provider

1) Storing of device tokens in your db / make api for this. It's a 1:n relation, since users can have several devices
2) Delete device tokens when Apple tells you they are invalid
3) The apps needs to keep a fresh token and send it to api, with plenty of errorhandling (No token, no push)
4) When you want to send push to many users, you have to loop device tokens. This will be very slow with 100k+ users, queues with many works should be used here to send out push at the same time. Providers do have this. Users recieve push notifications within seconds even at 100k+ scale
5) When you want to send a push to user 1, you need to look up all his device tokens and loop them, provididers have tagging systems. Send push to tag "user_id_1" fx
6) Build a log system to store send push and responses from apple. So you can actually debug possible errors
7) Dealing with several environments. Can use several push apps, with different certificates for sandbox, adhoc and production

On top of that you most likely want GCM / FCM / WNS support also. Which is more integrations, different rules.

You end up spending a lot of hours on building something worse than the providers.

Just like we use
- Mailgun for sending mails
- Twillio for sms
- Google for directions

For us it's all about spending our clients money on building unique software for their app. We use services for rest.

**Comment by anthonycastelli** [comment]
Tori (https://github.com/boostcode/Tori-APNS) looks like it might be worth checking out for APNS. Looks a bit more stripped down for basic push notifications

**Comment by matthijs2704** [comment]
Started doing some stuff over here https://github.com/matthijs2704/vapor-apns
Welcome to help! :)

Based on the new token authenticated push notifications, instead of certificates, only thing really needed now is a working HTTP/2 client...

**Comment by wildfiremedia** [comment]
Will GDC or libdispatch supported on APN which might start make sense for
heavy load.

On Mon, Sep 26, 2016 at 2:19 PM, Matthijs Logemann <notifications@github.com

**Comment by matthijs2704** [comment]
@wildfiremedia I'm creating this library/provider as a sync library. You can use GCD in your own code to make it async. But yes that is the thought! :)

**Comment by gregpardo** [comment]
It would be useful probably to have two libraries. One for the http client stuff to interact with Android and iOS push API and one to map with fluent to sync to the database and provide callbacks.

**Comment by petrpavlik** [comment]
I've quickly hacked together an SDK for Pusher's push notification API. Pusher currently provides free unlimited notifications, which makes this the most approachable way to make the notifications work (both iOS and Android) to my knowledge. I hope you find that useful.

https://pusher.com/push-notifications
https://github.com/petrpavlik/PusherNotificationsSwift

**Comment by matthijs2704** [comment]
I've also released VaporAPNS,An easy way to send APNS notifications in Vapor! :) https://github.com/matthijs2704/vapor-apns

**Comment by LoganWright** [comment]
We are opting to deprioritize this since @matthijs2704 and his vapor-apns package is currently fulfilling the role 👍

**Comment by mohpor** [comment]
I guess now that @matthijs2704's repo is extremely out of date, is ti time to reopen this? or will he approve the PRs already waiting to be upgraded to Swift 4 (and hopefully 4.2)?

**Comment by anthonycastelli** [comment]
There are two libraries for Push Notifications that I am working on, and that are both made for Vapor 3 and Swift 4.2
1. https://github.com/vapor-community/apns (Requires Vapor to Support HTTP/2 so for the time being, it doesn't work)
2. https://github.com/vapor-community/onesignal (Currently using this in a project of mine and does work)
Once I get the project off the ground I plan on finishing up the OneSignal version a bit more.

**Comment by mohpor** [comment]
@anthonycastelli  Thanks.
I'm currently working on adding a service to support sending push notifications through [GoRush](https://github.com/appleboy/gorush) via its REST API. It must be very straightforward. It supports both APNS And FCM and is very performant. I've a working Docker with GoRush for my app and I'm trying to migrate to Vapor for my backend.

**Comment by code28** [comment]
@mohpor That sounds quite interesting for me. Do you have an update on your progress? I'd be happy to take a look and help if I can.

**Comment by code28** [comment]
Maybe someone who's interested in this topic will come here and might use this:
I just released a service for [Gorush](
https://github.com/appleboy/gorush) to easily use this as proxy to send push notifications.
You can find it here: https://github.com/code28/vapor-gorush

I'm happy for feedback and contributions!

**Comment by kylebrowning** [comment]
@tanner0101 Since you last commented, this one has been built :)

https://github.com/kylebrowning/swift-nio-http2-apns
