### ISSUE TITLE
Client Request https

### ISSUE THREAD

**Issue by wei18810109052** [vapor/vapor#634]
I have a problem using [HTTP/Client](https://vapor.github.io/documentation/http/client.html#client).

```
       do {
            let spotifyResponse = try drop.client.get("https://api.weixin.qq.com/cgi-bin/token")    
            print(spotifyResponse)
        } catch let error  {
            print(error)
        }

```

get error like this.

```
send("handshake failed: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed")
```

But I make a same HTTP Request with NSURLConnection,It work well.

```
    let url = URL(string: "https://api.weixin.qq.com/cgi-bin/token")
        let urlRequest = URLRequest(url: url!)
        NSURLConnection.sendAsynchronousRequest(urlRequest, queue: OperationQueue.main, completionHandler: { (reponse, data, error) in
            let string = NSString(data: data!, encoding: String.Encoding.utf8.rawValue)
            print(string)
        })
```

I  also check it using postman.It work well too.

**I do not know where something went wrong.**

**Comment by darwind** [comment]
I got the exact same issue calling Google's Places API:

`https://maps.googleapis.com/maps/api/place/textsearch/json?query=restaurants&key=[apikey]&location=40.741895,-73.989308`

While using the Spotify URL (`https://api.spotify.com/v1/search?type=artist&q=test`) in the examples on https://vapor.github.io/documentation/http/client.html it works fine.

I've tried in the browser and the URL works fine.

**Comment by trustyourfish** [comment]
Unfortunately the only workaround I've found was disabling the verifyCertificates to false in Config\clients.json

**Comment by LoganWright** [comment]
@trustyourfish @darwind disabling the verify, or using NSURLSession for now should be good. I'm working on narrowing down the cause of this.

**Comment by andreasley** [comment]
@LoganWright There seems to be a problem verifying the issuer, because it isn't in the local trust store (`X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY`).

Running the command `openssl s_client -connect api.weixin.qq.com:443` shows the chain for `api.weixin.qq.com` to be as follows:
```
 0 s:/C=CN/ST=Guangdong/L=Shenzhen/O=Shenzhen Tencent Computer Systems Company Limited/OU=R&D/CN=mp.weixin.qq.com
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3
 1 s:/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
```

`mozilla_certs.pem` is missing `Equifax Secure Certificate Authority`. I think we could include the [root certificates from OpenBSD's LibreSSL](https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/cert.pem) instead of the ones from Mozilla; they pass all the tests and work with both URLs mentioned in this thread.
