### ISSUE TITLE
Localization: language header with relative quality factor is not handled

### ISSUE THREAD

**Issue by honghaoz** [vapor/vapor#655]
# Bugs

localization doesn't parse language header with relative quality factor correctly
E.g. `zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4`
## Introduction

Safari is sending single language code, e.g. `en-us`. Chrome is sending something like `zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4`.

**Comment by LoganWright** [comment]
@tannernelson this seems very similar to some of the accept/cookies stuff you added, can we use that code here?

**Comment by tannernelson** [comment]
Yup, we should be able to use the same logic. I'll look into this.

**Comment by Casperhr** [comment]
Not that PHP will help you that much, but we had a func like this we used for years. Never had an issue with it

```php
    function parse_accept_language(string $acceptLanguage) : array
    {
        // Prioritized languages
        $languages = [];
        // If we have a comma-separated language list
        // we'll wanna split them up into an array
        $acceptedLanguages = strstr($acceptLanguage, ',') ? explode(',',
            str_replace(' ', '', $acceptLanguage)) : [$acceptLanguage];
        // Parse each found language and generate
        // an array of prioritized languages
        foreach ($acceptedLanguages as $acceptedLanguage) {
            $acceptedLanguage = strstr($acceptedLanguage, ';') ? explode(';', $acceptedLanguage) : $acceptedLanguage;
            if (is_array($acceptedLanguage)) {
                $weight = explode('=', $acceptedLanguage[1])[1];
                $languages[(string)$weight][] = $acceptedLanguage[0];
            } else {
                $languages['1.0'][] = $acceptedLanguage;
            }
        }
        // Reverse sort priority list
        // 1.0 -> 0.0
        krsort($languages);
        return array_flatten($languages);
    }
```

Returns a list of ordered languages

**Comment by lorsulic** [comment]
any news about this issue here? Localization is not working inside firefox or chrome, currently only in safari.

**Comment by codesman** [comment]
@honghaoz `Request.acceptLanguage` does actually parse the `Accept-Language` header correctly, the problem is that Vapor doesn't do anything with that knowledge.

After looking into this a bit, I thought I'd report what I've found.  IMO, there appear to be multiple issues with Localization and HTML language attribute handling in Vapor but there are blurred lines between Vapor and app specific functionality.

It is certainly "possible" to implement correct handling with Vapor given what is there, but you don't get it "out the box" for free and it seems like Vapor should provide this versus making everybody roll their own, maybe not. Either that or remove Localization as a feature from Vapor and offer the current implementation as a module that could be used as a partially functional example for those that need to implement localization in their app.

There are 2 properties on Request that have to do with HTML Language.  `Request.acceptLanguage` and `Request.lang`

`Request.acceptLanguage` parses the `Accept-Language` header string into an `[AcceptLanguage]` while  `Request.lang` simply returns either the raw `Accept-Language` header string if it exists or “”.

I cannot find anywhere in Vapor where the `Request.acceptLanguage` array is used for anything. We are only using the `Request.lang` string as a subscript on the `localization` object which is just dictionary of all language strings.  This has several problems that I can see.

The first one is that we are trying to subscript the `localization` dictionary with `Request.lang`. This will ALWAYS fail if the `Accept-Language` header string exists and is not an exact match for a key in the localization dictionary. Which is the case with `zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4`

The second one is that there is no checking of the `acceptLangage` array against the localization dictionary to check to see if we have any matching localizations for any of the requested languages.

The third one is that it feels like a bad practice to be parsing all language files into memory on every request.  When we are just returning “It works” it’s not that bad, but seems like this could turn into a real performance issue on a text/translation heavy app, maybe not?  Perhaps we should determine which language(s) we are looking for and then parse the localization files if they exist.

The fourth one is that there is no “default” language in HTML or on earth! You must declare a valid language tag or an empty string if you want to be explicitly ambiguous - which is not recommended. `Localization.defaultDialect` should never equal “default” it should only ever be a valid language tag - that has a matching localization file or an error should be thrown.

The fifth one is that our example project templates do not include a `lang` attribute on the `<html>` element. If we are going to be dealing with localization, our templates must have this and we probably should be injecting this into the rendering context so that templates have easy access to it by default.

The sixth one is that we don’t return a `Content-Language` header that indicates the actual language(s) we are responding with.

The seventh one is using too specific of tags when they are not required.  This isn’t really a vapor problem per se, but it’s kinda like CSS, use as little specificity as you can. In the example project, the localization files are too specific. `nl-BE.json` and `nl-NL.json` both contain the same content and are the same language so their content should be in a file named `nl.json` that will be used whenever `nl` is requested.   If there are terms you need that are specific to Belgian Dutch, then you would add an additional `nl-BE.json` that contained only the specific Belgian Dutch strings. Currently in the example app, if `nl` is requested, we respond with `default` because there is no `nl.json` file.  If I understand the spec correctly, there should be no `xx-XX.json` file without a less-specific `xx.json`. Bottom line, if you are going to localize, start with `xx.json` and add regions/scripts etc. in additional files.

Also, don’t return a specific dialect if that dialect is not requested i.e. don’t return `en-US` if `en` was requested and conversely don’t request `en-US` when you really want ‘en’. The proper use of language tags is definitely a rabbit hole and even the authors of the spec say there is much work to be done there.

Perhaps we could have a middleware on the Request that uses `Request.acceptLanguage` to decide which of the requested languages we will respond with and then perhaps a `Localization.data(with: [AcceptLanguage])` method that returns a subscript-able dict of those languages and finally middleware for the Response that makes sure we return a correct and valid `Content-Language` header.

Going further, to properly support multiple languages in one page we would need to have some way of knowing if multiple languages have been used so we can form proper `lang` and `Content-Language’ responses. That one gets sticky real quick!

And then I will duck and cover before I finally mention that we’ve really only got a poor-man’s version of localization without variable tokens.  Seems that we need to implement something like `NSLocalizedString` or some more stuff in the localization subscript methods to handle this.

Hoo boy!

**Comment by tanner0101** [comment]
The accept header mentioned in the initial issue has been added to a test case to ensure it's working properly. As for the broader issue of localization, this will be coming as a separate package in the future. It has been removed from Vapor 2.0 until then.
