### ISSUE TITLE
Leaf: evaluating expressions inside if, then, else statements

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#682]
# Feature, Enhancement, or Optimization
# Evaluating expressions inside if, then, else statements
- Author(s): [Jeroen Wesbeek](https://github.com/4np)
- Subject: [Leaf templating](https://vapor.github.io/documentation/guide/leaf.html) 🍃
- Related to #680

## Introduction

It is currently not possible to do more than just basic `if`, `then`, `else` statements inside `Leaf` templates.

## Motivation

Conditions containing evaluations do not work (related to #680). 

```
#if(device.enabled == false) { disabled }
```

Nor do more advanced equations like these:

_inside controller:_

```
return try drop.view.make("myTemplate", [
    ...
    "model": myModel,
    "modelID": myModel.id,
    ...
])
```

_inside template `myTemplate.leaf`:_

```
#if(element == model) { this will not work }
#if(element.id == model.id) { nor does this }
#if(element.id == modelID) { or this }
```

## Proposed solution

Allow more advanced expressions inside `if`, `then`, `else` statements.

**Comment by LoganWright** [comment]
We're in the process of discussing this in the #leaf channel of our [slack](http://vapor.team), feel free to participate there. 

The number one question is whether or not any value is actually added by including this, for example, is there value to have this:

**Proposed**

```
#if(foo == "bar") {
```

and

```
context.set("foo", foo)
```

[1:41] 

**Current**

```
#if(foo)
```

```
context.set("foo", foo == bar)
```


for me, the desire to have the former is because other languages are basically executing code dynamically so it's more flexible, in swift, we'd basically have to build a compiler for anything complex and it makes code less safe.

Either way, discussion is ongoing, and feel free to join us in slack!
