### ISSUE TITLE
Toolbox fails to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by sebsto** [vapor/vapor#701]
## Problem

```
ubuntu@ip-172-31-26-52:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

ubuntu@ip-172-31-26-52:~$ curl -sL toolbox.vapor.sh | bash
✅  Compatible
Downloading...
Compiling...
/home/ubuntu/swift/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swift-build: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
Installing...
bash: line 22: .build/release/Executable: No such file or directory
Use vapor --help and vapor <command> --help to learn more.
```

## Fix : install libcurl openssl dev

```
ubuntu@ip-172-31-26-52:~$ sudo apt-get install libcurl4-openssl-dev
```

## Fixed

```
ubuntu@ip-172-31-26-52:~$ curl -sL toolbox.vapor.sh | bash
✅  Compatible
Downloading...
Compiling...
Installing...
Install failed, trying sudo
Vapor Toolbox v1.0.3 Installed
Use vapor --help and vapor <command> --help to learn more.

ubuntu@ip-172-31-26-52:~$ vapor --help
Usage: vapor <new|build|run|fetch|clean|test|xcode|version|self|heroku|docker>
Join our Slack if you have questions, need help,
or want to contribute: http://vapor.team
```

**Comment by LoganWright** [comment]
Thanks for providing an issue AND a fix, this is awesome @sebsto

**Comment by yura-voevodin** [comment]
root@ubuntu-512mb-nyc3-01:~# curl -sL toolbox.vapor.sh | bash
✅  Compatible
Downloading...
Compiling...
error: invalid inferred toolchain: could not find `clang`
Installing...
bash: line 22: .build/release/Executable: No such file or directory
Use vapor --help and vapor <command> --help to learn more.

**Comment by Xen0phobe** [comment]
I was getting a similar error when trying to start Gitkraken on Ubuntu 16.04:
> libcurl.so.4: cannot open shared object file: No such file or directory

Installing libcurl4-openssl-dev with the following command did the trick:
> sudo apt-get install libcurl4-openssl-dev

Thank you.

**Comment by cedricgannet** [comment]
I trhink the problem is with the name "libcurl.so.4".  I had a similar problem on Linux Mint 18 (base - Ubuntu 16.04), 64 bit, installing a new .deb file for software previously only available for Windoze.  The install was faultless but when I tried to run the programme, it failed with the message "error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory".

The supplier advised me to install "curl" but it was already there.  I fully uninstalled it then reinstalled without any change.  I then did a scan for libcurl.so.4 on my hard disk without result.  The nearest I could find for it were in /usr/lib/x86_64-linux-gnu/.  The files were "libcurl-gnutls.so.3", "libcurl-gnutls.so.4" and "libcurl-gnutls.so.4.4.0".  The first two being symlinks to the third.  I then added a further symlink to "libcurl-gnutls.so.4.4.0" called "libcurl.so.4" and this allowed me to run the new version without problems.

**Comment by Sammy2005** [comment]
This worked for me too. Great work man

**Comment by ezfe** [comment]
This issue, with the same resolution, is still happening to me with a new project template. Am I missing something or does it need to be re-applied to the templates?

**Comment by 0xTim** [comment]
@ezfe What are you trying? 16.04 is EoL and no longer supported

**Comment by ezfe** [comment]
I wasn't selecting 16, I believe the dockerfile said "focal" which is 20?

**Comment by 0xTim** [comment]
What are you trying to do and what steps are you following?

**Comment by 0xTim** [comment]
Right I see. This was added in https://github.com/vapor/template/pull/88

**Comment by ezfe** [comment]
Wonderful - thanks, that didn't show up in any searches 🙁
