### ISSUE TITLE
Compilation issue on Heroku

### ISSUE THREAD

**Issue by subdigital** [vapor/vapor#709]
I am migrating [NSDateFormatter.com](http://nsdateformatter.com) to Vapor (🎉), but I'm running into an issue.

The site works locally, but when deploying to heroku the app crashes and I see this in the logs:

>2016-11-19T03:37:32.811154+00:00 app[web.1]: Could not cast value of type 'Swift.String' (0x7f988d4ca648) to 'Foundation.NSString' (0x7f988d105780).

I can't tell what line this occurred on. In fact, it seems that the deploy succeeds but the first request fails.

I thought maybe it was because I didn't have a `.swift-version` in place, but after adding one with `3.0` I got the same result (also this appears to be the default version).

Do you have any other suggestions on what I might try? Alternatively I can host this on Digital Ocean (where the current site is), but wanted to leverage Heroku if I could get it working.

Thanks!  (side note: Vapor has come a _long_ way, congrats!)

**Comment by tannernelson** [comment]
Foundation on Linux is young and still a little buggy. :( What you're seeing here could be related to: https://bugs.swift.org/browse/SR-158. 

If you can, you should create another issue on the Swift JIRA for this particularly. 

For now, I'd recommend finding which line is causing this crash and explicitly casting the String or using a different method to format the date.

Closing this here since it's not an issue with Vapor. But feel free to reply here or in our Slack if you need help finding a workaround.

**Comment by subdigital** [comment]
Following up on this, it turns out to be a swift bug w/ `Locale.availableIdentifiers()`. I filed a bug on Swift here:  https://bugs.swift.org/browse/SR-3634.  As a workaround I was able to just use `CFLocaleCopyAvailableLocaleIdentifiers` and `unsafeBitcast` directly.
