### ISSUE TITLE
Missing information about how to implement Vapor outside of coveo-styleguide environment

### ISSUE THREAD

**Issue by frederik-labbe** [vapor/vapor#746]
**Enhancement**
It is confusing at first to understand what is needed to consider beside the markup that is shown on the landing page. This information could be useful for newbies:

- Wrap your markup inside a `.coveo-styleguide` wrapper, possibly the whole body if the styleguide is going to be used everywhere?
- A summary of what needs to be handled by the fork itself and what vapor will take care of. For example, for the modals it should be clear that the backdrop needs to be added to the example
- A list of relevant js modifiers for a control would also be interesting

**Comment by proyb6** [comment]
@frederik-labbe It can be confuse for you to post in the wrong project. You can repost on 
https://github.com/coveo/vapor

I would suggest it's the best time to use CSS flexbox instead of any CSS framework, you can write it easily for mobile, tablet and desktop screen and smaller code.
See which browsers supported: http://caniuse.com/#search=flexbox
See demo and one Javascript demo should give you an idea: https://umaar.github.io/css-flexbox-demo/

Vote to close this issue.
