### ISSUE TITLE
Accessing multipart files takes too much time

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#761]
To access my 2mb file takes about 10 seconds on my brand new mac and 156mb file about 15 mins ...
``` swift
guard let multipart: Multipart = request.multipart?["file"] else {
        // return missing data response
}
```
If I send the file as a binary `Body`, all is good.

**Comment by tannernelson** [comment]
@rafiki270 probably something in multipart needs to be optimized. I'll take a look.

**Comment by Casperhr** [comment]
@tannernelson im not getting this

The only way I can make it load for a bit with 2mb image, is to print it

**Comment by rafiki270** [comment]
@casperhr I am uploading an ipa and apk files (pretty much a zip file) ... I was thinking if it could be trying to parse json out of if by any chance before it fails and sends the data forward?

**Comment by tannernelson** [comment]
Yeah it looks like it could be JSON attempting to parse as mentioned here: https://github.com/vapor/vapor/issues/760

We might need to lazy load the JSON parsing or only attempt if the content-type contains JSON.

**Comment by tannernelson** [comment]
@rafiki270 it looks like the JSON is both being lazy loaded and also checking that the content-type contains JSON before attempting to parse.

Could you copy/paste the request you are sending (truncating the body since it's very long)?

Also, are you attempting to access `request.data` or `request.json` anywhere else in the route closure?

It could simply be that the current implementation of multipart needs to be more efficient.

Linking https://github.com/vapor/vapor/issues/734 since it's related as well.

**Comment by rafiki270** [comment]
I did notice the high CPU as well, it takes the whole 100% of the cpu for the time of the upload. Will check the rest later.
