### ISSUE TITLE
Re: Issue #747 (regex support)

### ISSUE THREAD

**Issue by CraigRhodes** [vapor/vapor#830]
Potentially add support for URI's that match specific regexes.
For example, Django and other Web App frameworks allow you to specify regexes that match specific URIs. Perhaps it would be something like:

```
let app = Droplet()
app.get("foo", Regex("[a-z]+"), Regex(".+")) { request in
     // code here
}
app.run()
```
which would match URIs such as /foo/bar/anything-goes-here

This would make the framework even more flexible I believe as it would allow you to group many different but similar URIs into a single, general function.

**Comment by tanner0101** [comment]
This should be possible by declaring a general `:param` or `"*"` route that catches all, then doing the regex logic inside of your route closure. Given that this is accomplishable w/o the need for additional syntax, I think this issue should be left to third parties to implement. Closing this for now, but feel free to re-open if you find not having this feature built in is preventing you from accomplishing something.

**Comment by revolter** [comment]
It's not the same thing because handling this in the route closure is later than the default route matching, meaning that you're most probably already inside a controller, which maybe isn't what you want.

Some examples of frameworks supporting this:
- [Laravel](https://laravel.com/docs/5.1/routing#parameters-regular-expression-constraints)
- [Yii](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#named-parameters)
- [Django](https://docs.djangoproject.com/en/2.0/topics/http/urls/#using-regular-expressions)
- [Ruby on Rails](http://guides.rubyonrails.org/routing.html#specifying-constraints)
- [Symfony](https://symfony.com/doc/current/routing.html)

**Comment by bhakterija** [comment]
What about cases when you need to have variable parameters only, no fixed prefix?
I tried matching simple route "/en/2018" with
```
    func build(_ builder: RouteBuilder) throws {
        builder.get(":langId", ":year") { req in
            guard let langId = req.parameters["langId"]?.string else {
                throw Abort.badRequest
            }
            guard let year = req.parameters["year"]?.string else {
                throw Abort.badRequest
            }
            return "langId: \(langId) / year: \(year)"
        }
```
and it took over built-in routes, like `/styles/` and `/images/`.

Now request to http://localhost:8080/images/it-works.png returns text "langId: images / year: it-works.png" instead of the png image.

A regex matching would cover this case.

**Comment by twof** [comment]
@bhakterija  Someone else correct me if I'm wrong, but I think this is fixed in Vapor 3 with parameter type conformance

**Comment by bhakterija** [comment]
@twof 
Trying this:
```
builder.get(String.parameter, Int.parameter) { req in
            let langId = try req.parameters.next(String.self)
            let year = try req.parameters.next(Int.self)
            return "langId: \(langId) / year: \(year)"
        }
```
Still overrides built-in routes, despite the type mismatch.
http://localhost:8080/images/it-works.png returns `langId: images / year: it-works.png`
Or am I missing something here?

**Comment by twof** [comment]
Nah you're right. That seems like it ought to be correct. Can you share your `package.swift` please?

**Comment by bhakterija** [comment]
@twof 
I edited my previous post. It does check types inside `get()`, but it's a bit too late at this point.
I wish it could do route matching by type and dismiss my route as non matching.

**Comment by twof** [comment]
You have /images/it-works.png inside your `Public` directory right?

**Comment by twof** [comment]
This is the folder structure I have and it's serving the image at `localhost:8080/image/Adventure.jpg`

![image](https://user-images.githubusercontent.com/5561501/34842934-df2be324-f6c1-11e7-8f07-c33fa0196419.png)

**Comment by bhakterija** [comment]
Thanks, @twof 
I'm playing with vanilla project generated by vapor with `--template=web` parameter.
The only change is my route. If I comment it out, everything works fine.

**Comment by twof** [comment]
huh that's really weird. I'll give your setup a try when I get home later.

**Comment by twof** [comment]
Yeah definitely a bug. I've submitted a report here: https://github.com/vapor/vapor/issues/1427

If you have any new info about the bug, you can log it there and it should get fixed.
