### ISSUE TITLE
Support for Xcode-beta (Swift 3.1)?

### ISSUE THREAD

**Issue by treaves** [vapor/vapor#836]
I'm using the current Xcode beta.  It uses Swift 3.1, not 3.0.  This - oddly -breaks things.  Not because of any incompatible - or more correctly, I don't get far enough to tell if there is an incompatibility.  It breaks merely because of a string comparison of 3.1 != 3.0.

Is it really the intended behavior for Vapor to break with every minor release of Swift?

**Comment by tanner0101** [comment]
> It breaks merely because of a string comparison of 3.1 != 3.0.

Could you elaborate on this? 

> Is it really the intended behavior for Vapor to break with every minor release of Swift?

No.

**Comment by linqingmo** [comment]
I used Xcode beta, and now I'm using Xcode beta2, Vapor works fine.

**Comment by treaves** [comment]
With Xcode 8 .3 beta 2:
- When I opened an existing project in Xcode, Vapor was not found.  So every Vapor import statement produced and error.
- I ran 'vapor Xcode' to product a new Xcode project, and it failed, with the error it was exception Swift version 3.0, but found 3.1. (I can not re-create this.  After switching back and forth several times, it seems to be working).
- I re-ran Xcode-select to select the prior version. Generated the project.
-- Now, when I open the Xcode project, all I see under the Sources group is App.  This is all I really expect to see, however, prior to this, I'd see App and every modules source as well.  So this is at least a difference. (Switching between Xcode 8.2 and the beta still exhibit the behavior; one shows the modules , the beta does not).
-- When running the project under Xcode beta, my 'Config/servers.json' file is ignored.  Starting the app always starts in listening on port 8080, instead of the port defined. (again, this is recreate-able behavior).

**Comment by tanner0101** [comment]
Looks like this is an issue with https://github.com/vapor/toolbox. Probably that the installer checks to make sure you have Swift 3.0 installed. We need to widen this to accept anything >= 3.0. 

As for the module folders, that's a known bug in SPM in Swift 3.0 and was fixed in 3.1.

For the `Config/servers.json` issue, that is most likely caused from SPM changing how it stores the `Packages` folder. I believe they moved it under the `.build` folder now. This means we will need to change how we automatically parse the working directory. Until then, you can manually pass `--workDir=/path/to/project` to Vapor through Xcode arguments.

**Comment by tanner0101** [comment]
https://github.com/vapor/toolbox/issues/138
