### ISSUE TITLE
IncorrectCredentialsError and AccountTakenError don't go through in .production mode

### ISSUE THREAD

**Issue by truemetal** [vapor/vapor#930]
I'm not sure if that's by design or actually a bug. Throwing `AccountTakenError`, `IncorrectCredentialsError` and similar make no appearance in resulting json.

Due to the fact that those extremely handy error types are not `AbortError`, `AbortMiddleware` replaces their error message with `Something went wrong` when in `.production` mode 

I'm working that around this like so for now: 
```
let myAccountTaken = Abort.custom(status: .badRequest, message: AccountTakenError().description)
let myIncorrectCredentialsError = Abort.custom(status: .badRequest, message: IncorrectCredentialsError().description)
```

**Comment by tanner0101** [comment]
@truemetal it's by design that only `Abort` errors are shown in production mode. This prevents errors containing sensitive data from being displayed publicly. 

The workaround you have posted is great 👍 

Another possible method is to add a middleware that catches your custom errors and turns them into Abort errors.

Something like

```swift
do {
    return try next.respond(to: req)
} catch MyCustomError {
    throw Abort.badRequest
}
```
