### ISSUE TITLE
Vapor on Ubuntu 16.04 armhf doesn't install

### ISSUE THREAD

**Issue by darthpelo** [vapor/vapor#958]
Hi, since the `curl -sL toolbox.vapor.sh | bash` is deprecated, it's not more possibile to install and use Vapor with Ubuntu 16.04 armhf (Raspberry Pi boards for example).

After added `https://apt.vapor.sh` with `eval "$(curl -sLhttps://apt.vapor.sh)"` the `sudo apt-get update` returns this error:
`N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://repo.vapor.codes/apt xenial InRelease' doesn't support architecture 'armhf'`

Of course `sudo apt-get install vapor` fails because apt-get cannot finds vapor package.

Is it possible to add the ARM support to the repository? Or reactivate the old toolbox.vapor.sh script?

Thanks

**Comment by darthpelo** [comment]
My bad, the issue is related to toolbox, not vapor. Sorry.

**Comment by ohayon** [comment]
Hey @darthpelo , what was the fix for this?

**Comment by vzsg** [comment]
Swift on ARM is completely unsupported and requires much more patience and higher pain tolerance. Whatever you find about using Vapor on Ubuntu doesn't directly apply.

1. You need to install the Swift toolchain manually – the package available from [here](https://github.com/uraimo/buildSwiftOnARM) has worked for me in the past.
1. If you want the Vapor Toolbox (I recommend learning the `swift package` commands instead), you'll have to build it yourself by cloning https://github.com/vapor/toolbox.git, checking out `tags/2.0.3`, doing a release build and moving the resulting executable to `/usr/bin/vapor`.
1. Then using the Vapor project templates is a new dance, as both the api-template and the web-template were updated to require Swift 4. Instead of using `vapor new`, you'll have to clone a template repo, roll it back before the Swift 4 update, remove the .git folder and enjoy.

It's a real pity that Swift 4 is [not compatible](https://github.com/uraimo/buildSwiftOnARM/issues/5) with armhf; and as far as relevant activity shows, no one cares anymore. This makes the whole exercise futile IMHO.

**Comment by ohayon** [comment]
Thanks @vzsg - yeah installing swift was no problem. I was confused about installing vapor as I didnt realize it was a separate repo (toolbox). Thanks!
