### ISSUE TITLE
Improved Config

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#971]
### Introduction

* Author(s): [Tanner](https://github.com/tanner0101)

This proposal is about expanding and improving upon the current Droplet configuration system to make configuration less confusing, more testable, and to handle edge-cases better.

Currently, all Droplet properties are variable. They can be changed at any point after the Droplet is initialized. Additionally, providers are added directly to the Droplet.

```swift
import Vapor
import MySQLProvider

let drop = try Droplet()

try drop.addProvider(MySQLProvider.Provider.self)
drop.log = MyLogger()

...
```

This document proposes using the `Config` object for this type of configuration, allowing the Droplet to have static properties.

```swift
import Vapor
import MySQLProvider

let config = Config()

try config.addProvider(MySQLProvider.Provider.self)
config.log = MyLogger()

let drop = try Droplet(config)

drop.log = MyOtherLogger() // error
...
```

### Motivation

Since Droplet properties are variable, passing a Droplet service (such as log) to a class or struct that requires it may sometime not behave as expected. 

```swift
import Vapor
import LeafProvider

let drop = try Droplet()

let controller = Controller(drop.view)

drop.addProvider(LeafProvider.Provider.self)
```

In the above example, the `Controller` gets a pointer to the Droplet's `ViewRenderer`. This is set to `StaticViewRenderer` when the Droplet is initialized.

However, later the `LeafProvider` is added which supplies a `LeafRenderer`. `drop.view` now points to a `LeafRenderer`.

Most likely, the `Controller` will have wanted access to the `LeafRenderer` and thus a confusing bug has resulted.

Additionally, things like middleware ordering are currently impossible respect from config files.

### Code snippets

```swift
struct Configurable {
    enum Kind {
        case database
        case cache
        case log
        case view
        ...
    }

    var name: String
    var kind: Kind
    var object: ConfigInitializable.Type
}
```

```swift
extension Config {
    var configurables: [Configurable]
}
```

```swift
final class LeafProvider {
    init(_ config: Config) {
        config.configurables += [
            Configurable(name: "leaf", kind: .view, object: LeafRenderer.self)
        ]
    }
}
```

```swift
extension Config {
    func resolveConfigurable(for kind: Configurable.Kind) -> Configurable {
        let chosen = self.name(for: kind)
        let matches = configurables.filter {
            return $0.kind == kind && $0.name == chosen
        }

        guard matches.count < 2 {
            // throw error for too many matching
        }

        guard let first = matches.first else {
            // throw error about none matching
        }

        return first
    }
}
```

```swift
extension Droplet {
    convenience init(_ config: Config) throws {
        try self.init(
            database: try config.resolveConfigurable(for: .database),
            view: try config.resolveConfigurable(for: .view),
            ...
        )
    }
}
```

#### Depends

The `Configurable` type could have an added array `dependsOn: [Configurable.Kind]`. If one configurable kind depends on another configurable kind, that would cause the parent to be resolved first. Infinite loops could be detected by a counter to indicate unresolvable dependencies.

```swift
final class FluentProvider {
    init(_ config: Config) {
        config.configurables += [
            Configurable(name: "fluent", kind: .cache, object: FluentCache.self, dependsOn: [.database])
        ]
    }
}
```

This would allow support for things like `FluentCache` that rely on `Database` to be properly initialized without needing workarounds.

```swift
extension FluentCache: ConfigInitializable {
    init(_ config: Config) throws {
        guard let db = config.database else {
            // throw error that db is needed
        }

        self.init(db)
    }
}
```

**Comment by ghecho** [comment]
I'm not sure if this is the best place to discuss this but considering this would effectively make the droplet configuration non variable and would have to be set before the droplet routes (or maybe I'm missing something here and one could define the droplet routes first and later add the whole configuration?).

Well, the issue I see is: In Laravel for example (I know, stupid PHP 😞) you can specify certain routes or routes groups to have a specific set of middleware. As far as I can tell (I couldn't find anything in the documentation) in Vapor you can only specify a global set of middleware for all routes. It would be great to have the flexibility of having a specific middleware to be used only in certain routes. This allows for example to specify for example:

- /api/* route group (APIMiddleware that checks that the request has a valid api_token, else abort the request)
- /web or / (AuthMiddleware that checks that a user is logged in to view the site or else shows a login/sign up page)
- /admin/* route group (AdminMiddleware that checks that all admin pages are only viewed by Admin users, else redirect to home or root)

Returning to the config proposal, what would be the way of specifying this in the new proposed configuration?, maybe an optional parameter in the middleware registration in the new configuration?

I don't know the answer. Maybe at the time of registering a route or group specifying an array of middleware objects to be used? I think this would be a better option because it generates less code (I think).

What do you think? I don't want to go back to Laravel for my projects 😂

P.D. I think Laravel is a great framework, it's PHP the one that should be avoided like the plague.

**Comment by hhanesand** [comment]
[You can still add middleware per route with this change!](http://beta.docs.vapor.codes/routing/group/#middleware)

**Comment by ghecho** [comment]
Oh, thanks. I didn't see that. I'll try it later.

**Comment by LoganWright** [comment]
Upgraded and integrated 👍
